services:
  - type: web
    name: nexus-bot
    env: python
    buildCommand: apt-get install -y ffmpeg && pip install -r requirements.txt
    startCommand: python -m db.migrate && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PRIMARY_BOT_TOKEN
        sync: false
      - key: CLONE_TOKENS
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: SUPABASE_CONNECTION_STRING
        sync: false
      - key: OWNER_ID
        sync: false
      - key: SKIP_AUTH
        value: "false"
      - key: DEBUG
        value: "false"
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: RENDER_EXTERNAL_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: REDIS_URL
        sync: false
      - key: PYROGRAM_API_ID
        sync: false
      - key: PYROGRAM_API_HASH
        sync: false
      - key: RENDER_GIT_COMMIT
        sync: false
    healthCheckPath: /
    autoDeploy: true

  - type: worker
    name: nexus-music
    env: python
    buildCommand: apt-get install -y ffmpeg && pip install -r requirements.txt
    startCommand: python music_service.py
    envVars:
      - key: SUPABASE_CONNECTION_STRING
        sync: false
      - key: REDIS_URL
        sync: false
      - key: PYROGRAM_API_ID
        sync: false
      - key: PYROGRAM_API_HASH
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.9"
    autoDeploy: true
