# Database operations
from db.ops.groups import get_group, upsert_group, update_group_settings
from db.ops.users import add_warn, remove_warn, update_user_status, get_user
from db.ops.logs import log_action
from db.ops.bots import (
    get_all_active_bots,
    get_bot_by_id,
    insert_bot,
    update_bot_status,
    get_bot_by_token_hash,
    get_primary_bot,
    get_bots_by_owner,
    update_bot_last_seen,
    update_bot_groups_count,
    delete_bot,
    count_recent_clone_attempts,
    log_clone_attempt,
)
from db.ops.channels import link_channel, unlink_channel, get_linked_channel, get_channel_posts
from db.ops.modules import get_modules, set_module
from db.ops.captcha import (
    create_challenge,
    get_challenge_by_id,
    get_pending_challenge,
    mark_challenge_passed,
    increment_attempts,
    log_member_event,
)
from db.ops.booster import (
    get_boost_config,
    save_boost_config,
    get_boost_stats,
    get_boost_record,
    create_boost_record,
    update_invite_count,
    set_unlocked,
    set_restricted,
    set_exempted,
    reset_boost_record,
    get_all_boost_records,
    get_restricted_members,
    get_exempted_users,
    grant_access,
    revoke_access,
    record_invite_event,
    get_invited_by,
    get_user_invites,
    get_recent_invite_events,
    create_credit_request,
    get_pending_credit_requests,
    get_credit_request,
    approve_credit_request,
    deny_credit_request,
    record_manual_add,
    get_unassigned_adds,
    get_recent_manual_adds,
    assign_manual_add_credit,
    get_channel_gate_config,
    save_channel_gate_config,
    get_channel_stats,
    get_channel_record,
    create_channel_record,
    set_channel_verified,
    set_channel_restricted,
    get_unverified_channel_users,
    delete_channel_record,
    delete_all_channel_records,
)
