"""
bot/utils/localization.py

Localization system for Nexus Bot v21.
Supports 11 languages: en, ar, es, fr, hi, pt, ru, tr, id, de, th

No paid API used - all strings are hardcoded for reliability.
"""

import logging
from typing import Optional

logger = logging.getLogger(__name__)

# Supported languages
SUPPORTED_LANGUAGES = {
    "en": "English",
    "ar": "العربية (Arabic)",
    "es": "Español (Spanish)",
    "fr": "Français (French)",
    "hi": "हिन्दी (Hindi)",
    "pt": "Português (Portuguese)",
    "ru": "Русский (Russian)",
    "tr": "Türkçe (Turkish)",
    "id": "Bahasa Indonesia (Indonesian)",
    "de": "Deutsch (German)",
    "th": "ไทย (Thai)",
}

# Default language
DEFAULT_LANG = "en"

# String translations - Complete v21 catalogue
STRINGS = {
    # ============================================
    # WELCOME / GOODBYE
    # ============================================
    "welcome": {
        "en": "👋 Welcome {name} to {group}!",
        "ar": "👋 أهلاً وسهلاً {name} في {group}!",
        "es": "👋 ¡Bienvenido {name} a {group}!",
        "fr": "👋 Bienvenue {name} dans {group}!",
        "hi": "👋 {group} में आपका स्वागत है {name}!",
        "pt": "👋 Bem-vindo {name} ao {group}!",
        "ru": "👋 Добро пожаловать, {name}, в {group}!",
        "tr": "👋 {group}'a hoş geldin {name}!",
        "id": "👋 Selamat datang {name} di {group}!",
        "de": "👋 Willkommen {name} in {group}!",
        "th": "👋 ยินดีต้อนรับ {name} สู่ {group}!",
    },
    "goodbye": {
        "en": "👋 Goodbye {name}!",
        "ar": "👋 مع السلامة {name}!",
        "es": "👋 ¡Adiós {name}!",
        "fr": "👋 Au revoir {name}!",
        "hi": "👋 अलविदा {name}!",
        "pt": "👋 Adeus {name}!",
        "ru": "👋 До свидания, {name}!",
        "tr": "👋 Güle güle {name}!",
        "id": "👋 Sampai jumpa {name}!",
        "de": "👋 Auf Wiedersehen {name}!",
        "th": "👋 ลาก่อน {name}!",
    },
    # ============================================
    # WARN / UNWARN
    # ============================================
    "warn_issued": {
        "en": "⚠️ <b>Warning Issued</b>\nUser: {name}\nReason: {reason}\nCount: {count}/{max}",
        "ar": "⚠️ <b>تحذير صادر</b>\nالمستخدم: {name}\nالسبب: {reason}\nالعدد: {count}/{max}",
        "es": "⚠️ <b>Advertencia Emitida</b>\nUsuario: {name}\nRazón: {reason}\nConteo: {count}/{max}",
        "fr": "⚠️ <b>Avertissement Émis</b>\nUtilisateur: {name}\nRaison: {reason}\nCompte: {count}/{max}",
        "hi": "⚠️ <b>चेतावनी जारी</b>\nउपयोगकर्ता: {name}\nकारण: {reason}\nसंख्या: {count}/{max}",
        "pt": "⚠️ <b>Aviso Emitido</b>\nUsuário: {name}\nMotivo: {reason}\nContagem: {count}/{max}",
        "ru": "⚠️ <b>Предупреждение Выдано</b>\nПользователь: {name}\nПричина: {reason}\nСчёт: {count}/{max}",
        "tr": "⚠️ <b>Uyarı Verildi</b>\nKullanıcı: {name}\nSebep: {reason}\nSayı: {count}/{max}",
        "id": "⚠️ <b>Peringatan Diberikan</b>\nPengguna: {name}\nAlasan: {reason}\nJumlah: {count}/{max}",
        "de": "⚠️ <b>Warnung Ausgestellt</b>\nBenutzer: {name}\nGrund: {reason}\nAnzahl: {count}/{max}",
        "th": "⚠️ <b>คำเตือน</b>\nผู้ใช้: {name}\nเหตุผล: {reason}\nจำนวน: {count}/{max}",
    },
    "warn_max_reached": {
        "en": "🚫 <b>Max Warnings Reached!</b>\nUser {name} has reached {max} warnings.\nAction: {action}",
        "ar": "🚫 <b>تم الوصول للحد الأقصى!</b>\nوصل المستخدم {name} إلى {max} تحذيرات.\nالإجراء: {action}",
        "es": "🚫 <b>¡Máximo de Advertencias Alcanzado!</b>\nEl usuario {name} ha alcanzado {max} advertencias.\nAcción: {action}",
        "fr": "🚫 <b>Nombre Max d'Avertissements Atteint!</b>\nL'utilisateur {name} a atteint {max} avertissements.\nAction: {action}",
        "hi": "🚫 <b>अधिकतम चेतावनियाँ पूर्ण!</b>\nउपयोगकर्ता {name} ने {max} चेतावनियाँ पूरी कर ली हैं।\nकार्रवाई: {action}",
        "pt": "🚫 <b>Máximo de Avisos Atingido!</b>\nO usuário {name} atingiu {max} avisos.\nAção: {action}",
        "ru": "🚫 <b>Достигнуто Макс. Предупреждений!</b>\nПользователь {name} получил {max} предупреждений.\nДействие: {action}",
        "tr": "🚫 <b>Maks Uyarı Sayısına Ulaşıldı!</b>\n{name} kullanıcısı {max} uyarıya ulaştı.\nEylem: {action}",
        "id": "🚫 <b>Batas Maks Peringatan Tercapai!</b>\nPengguna {name} telah mencapai {max} peringatan.\nTindakan: {action}",
        "de": "🚫 <b>Maximale Warnungen Erreicht!</b>\nBenutzer {name} hat {max} Warnungen erreicht.\nAktion: {action}",
        "th": "🚫 <b>ถึงขีดจำกัดคำเตือน!</b>\nผู้ใช้ {name} ได้รับคำเตือน {max} ครั้งแล้ว\nการกระทำ: {action}",
    },
    "warn_removed": {
        "en": "✅ <b>Warning Removed</b>\nUser: {name}\nRemaining: {count}",
        "ar": "✅ <b>تم إزالة التحذير</b>\nالمستخدم: {name}\nالمتبقي: {count}",
        "es": "✅ <b>Advertencia Eliminada</b>\nUsuario: {name}\nRestantes: {count}",
        "fr": "✅ <b>Avertissement Supprimé</b>\nUtilisateur: {name}\nRestants: {count}",
        "hi": "✅ <b>चेतावनी हटा दी गई</b>\nउपयोगकर्ता: {name}\nशेष: {count}",
        "pt": "✅ <b>Aviso Removido</b>\nUsuário: {name}\nRestantes: {count}",
        "ru": "✅ <b>Предупреждение Снято</b>\nПользователь: {name}\nОсталось: {count}",
        "tr": "✅ <b>Uyarı Kaldırıldı</b>\nKullanıcı: {name}\nKalan: {count}",
        "id": "✅ <b>Peringatan Dihapus</b>\nPengguna: {name}\nTersisa: {count}",
        "de": "✅ <b>Warnung Entfernt</b>\nBenutzer: {name}\nVerbleibend: {count}",
        "th": "✅ <b>ลบคำเตือน</b>\nผู้ใช้: {name}\nเหลืออยู่: {count}",
    },
    # ============================================
    # BAN / KICK / MUTE
    # ============================================
    "user_banned": {
        "en": "🚫 <b>User Banned</b>\nUser: {name}\nReason: {reason}",
        "ar": "🚫 <b>المستخدم محظور</b>\nالمستخدم: {name}\nالسبب: {reason}",
        "es": "🚫 <b>Usuario Baneado</b>\nUsuario: {name}\nRazón: {reason}",
        "fr": "🚫 <b>Utilisateur Banni</b>\nUtilisateur: {name}\nRaison: {reason}",
        "hi": "🚫 <b>उपयोगकर्ता प्रतिबंधित</b>\nउपयोगकर्ता: {name}\nकारण: {reason}",
        "pt": "🚫 <b>Usuário Banido</b>\nUsuário: {name}\nMotivo: {reason}",
        "ru": "🚫 <b>Пользователь Заблокирован</b>\nПользователь: {name}\nПричина: {reason}",
        "tr": "🚫 <b>Kullanıcı Yasaklandı</b>\nKullanıcı: {name}\nSebep: {reason}",
        "id": "🚫 <b>Pengguna Diblokir</b>\nPengguna: {name}\nAlasan: {reason}",
        "de": "🚫 <b>Benutzer Gebannt</b>\nBenutzer: {name}\nGrund: {reason}",
        "th": "🚫 <b>ผู้ใช้ถูกแบน</b>\nผู้ใช้: {name}\nเหตุผล: {reason}",
    },
    "user_unbanned": {
        "en": "✅ <b>User Unbanned</b>\nUser: {name}",
        "ar": "✅ <b>تم إلغاء حظر المستخدم</b>\nالمستخدم: {name}",
        "es": "✅ <b>Usuario Desbaneado</b>\nUsuario: {name}",
        "fr": "✅ <b>Utilisateur Débanni</b>\nUtilisateur: {name}",
        "hi": "✅ <b>उपयोगकर्ता प्रतिबंध हटाया</b>\nउपयोगकर्ता: {name}",
        "pt": "✅ <b>Usuário Desbanido</b>\nUsuário: {name}",
        "ru": "✅ <b>Пользователь Разблокирован</b>\nПользователь: {name}",
        "tr": "✅ <b>Kullanıcı Yasağı Kaldırıldı</b>\nKullanıcı: {name}",
        "id": "✅ <b>Blokir Pengguna Dibuka</b>\nPengguna: {name}",
        "de": "✅ <b>Benutzer Entbannt</b>\nBenutzer: {name}",
        "th": "✅ <b>ยกเลิกการแบนผู้ใช้</b>\nผู้ใช้: {name}",
    },
    "user_kicked": {
        "en": "👢 <b>User Kicked</b>\nUser: {name}\nReason: {reason}",
        "ar": "👢 <b>تم طرد المستخدم</b>\nالمستخدم: {name}\nالسبب: {reason}",
        "es": "👢 <b>Usuario Expulsado</b>\nUsuario: {name}\nRazón: {reason}",
        "fr": "👢 <b>Utilisateur Expulsé</b>\nUtilisateur: {name}\nRaison: {reason}",
        "hi": "👢 <b>उपयोगकर्ता निकाला गया</b>\nउपयोगकर्ता: {name}\nकारण: {reason}",
        "pt": "👢 <b>Usuário Expulso</b>\nUsuário: {name}\nMotivo: {reason}",
        "ru": "👢 <b>Пользователь Исключён</b>\nПользователь: {name}\nПричина: {reason}",
        "tr": "👢 <b>Kullanıcı Atıldı</b>\nKullanıcı: {name}\nSebep: {reason}",
        "id": "👢 <b>Pengguna Ditendang</b>\nPengguna: {name}\nAlasan: {reason}",
        "de": "👢 <b>Benutzer Entfernt</b>\nBenutzer: {name}\nGrund: {reason}",
        "th": "👢 <b>เตะผู้ใช้</b>\nผู้ใช้: {name}\nเหตุผล: {reason}",
    },
    "user_muted": {
        "en": "🔇 <b>User Muted</b>\nUser: {name}\nDuration: {duration}",
        "ar": "🔇 <b>تم كتم المستخدم</b>\nالمستخدم: {name}\nالمدة: {duration}",
        "es": "🔇 <b>Usuario Silenciado</b>\nUsuario: {name}\nDuración: {duration}",
        "fr": "🔇 <b>Utilisateur Muté</b>\nUtilisateur: {name}\nDurée: {duration}",
        "hi": "🔇 <b>उपयोगकर्ता म्यूट किया गया</b>\nउपयोगकर्ता: {name}\nअवधि: {duration}",
        "pt": "🔇 <b>Usuário Mutado</b>\nUsuário: {name}\nDuração: {duration}",
        "ru": "🔇 <b>Пользователь Заглушён</b>\nПользователь: {name}\nДлительность: {duration}",
        "tr": "🔇 <b>Kullanıcı Susturuldu</b>\nKullanıcı: {name}\nSüre: {duration}",
        "id": "🔇 <b>Pengguna Dibisukan</b>\nPengguna: {name}\nDurasi: {duration}",
        "de": "🔇 <b>Benutzer Stummgeschaltet</b>\nBenutzer: {name}\nDauer: {duration}",
        "th": "🔇 <b>ปิดเสียงผู้ใช้</b>\nผู้ใช้: {name}\nระยะเวลา: {duration}",
    },
    "user_unmuted": {
        "en": "🔊 <b>User Unmuted</b>\nUser: {name}",
        "ar": "🔊 <b>تم إلغاء كتم المستخدم</b>\nالمستخدم: {name}",
        "es": "🔊 <b>Usuario Desilenciado</b>\nUsuario: {name}",
        "fr": "🔊 <b>Utilisateur Démuté</b>\nUtilisateur: {name}",
        "hi": "🔊 <b>उपयोगकर्ता अनम्यूट किया गया</b>\nउपयोगकर्ता: {name}",
        "pt": "🔊 <b>Usuário Desmutado</b>\nUsuário: {name}",
        "ru": "🔊 <b>Пользователь Разглушён</b>\nПользователь: {name}",
        "tr": "🔊 <b>Kullanıcının Susturulması Kaldırıldı</b>\nKullanıcı: {name}",
        "id": "🔊 <b>Pembisuan Pengguna Dibuka</b>\nPengguna: {name}",
        "de": "🔊 <b>Benutzer Entstummt</b>\nBenutzer: {name}",
        "th": "🔊 <b>ยกเลิกการปิดเสียง</b>\nผู้ใช้: {name}",
    },
    # ============================================
    # CAPTCHA
    # ============================================
    "captcha_prompt": {
        "en": "🔐 <b>CAPTCHA Verification</b>\nPlease verify you're human by clicking the button below.",
        "ar": "🔐 <b>التحقق من CAPTCHA</b>\nيرجى التحقق من أنك إنسان بالنقر على الزر أدناه.",
        "es": "🔐 <b>Verificación CAPTCHA</b>\nPor favor verifica que eres humano haciendo clic en el botón de abajo.",
        "fr": "🔐 <b>Vérification CAPTCHA</b>\nVeuillez vérifier que vous êtes humain en cliquant sur le bouton ci-dessous.",
        "hi": "🔐 <b>CAPTCHA सत्यापन</b>\nकृपया नीचे दिए बटन पर क्लिक करके सत्यापित करें कि आप मानव हैं।",
        "pt": "🔐 <b>Verificação CAPTCHA</b>\nPor favor, verifique que você é humano clicando no botão abaixo.",
        "ru": "🔐 <b>Проверка CAPTCHA</b>\nПожалуйста, подтвердите, что вы человек, нажав кнопку ниже.",
        "tr": "🔐 <b>CAPTCHA Doğrulaması</b>\nLütfen aşağıdaki butona tıklayarak insan olduğunuzu doğrulayın.",
        "id": "🔐 <b>Verifikasi CAPTCHA</b>\nSilakan verifikasi bahwa Anda manusia dengan mengklik tombol di bawah.",
        "de": "🔐 <b>CAPTCHA-Verifizierung</b>\nBitte verifizieren Sie, dass Sie ein Mensch sind, indem Sie auf die Schaltfläche unten klicken.",
        "th": "🔐 <b>ตรวจสอบ CAPTCHA</b>\nกรุณายืนยันว่าคุณเป็นมนุษย์โดยคลิกปุ่มด้านล่าง",
    },
    "captcha_passed": {
        "en": "✅ <b>CAPTCHA Passed!</b>\nWelcome {name}! You can now chat.",
        "ar": "✅ <b>تم اجتياز CAPTCHA!</b>\nأهلاً {name}! يمكنك الآن الدردشة.",
        "es": "✅ <b>¡CAPTCHA Aprobado!</b>\n¡Bienvenido {name}! Ya puedes chatear.",
        "fr": "✅ <b>CAPTCHA Réussi!</b>\nBienvenue {name}! Vous pouvez maintenant discuter.",
        "hi": "✅ <b>CAPTCHA पास!</b>\nस्वागत है {name}! अब आप चैट कर सकते हैं।",
        "pt": "✅ <b>CAPTCHA Aprovado!</b>\nBem-vindo {name}! Agora você pode conversar.",
        "ru": "✅ <b>CAPTCHA Пройдена!</b>\nДобро пожаловать, {name}! Теперь вы можете общаться.",
        "tr": "✅ <b>CAPTCHA Başarılı!</b>\nHoş geldin {name}! Artık sohbet edebilirsin.",
        "id": "✅ <b>CAPTCHA Lulus!</b>\nSelamat datang {name}! Anda sekarang dapat mengobrol.",
        "de": "✅ <b>CAPTCHA Bestanden!</b>\nWillkommen {name}! Sie können jetzt chatten.",
        "th": "✅ <b>ผ่าน CAPTCHA!</b>\nยินดีต้อนรับ {name}! คุณสามารถแชทได้แล้ว",
    },
    "captcha_failed": {
        "en": "❌ <b>CAPTCHA Failed!</b>\nPlease try again.",
        "ar": "❌ <b>فشل CAPTCHA!</b>\nيرجى المحاولة مرة أخرى.",
        "es": "❌ <b>¡CAPTCHA Fallido!</b>\nPor favor intenta de nuevo.",
        "fr": "❌ <b>CAPTCHA Échoué!</b>\nVeuillez réessayer.",
        "hi": "❌ <b>CAPTCHA विफल!</b>\nकृपया पुनः प्रयास करें।",
        "pt": "❌ <b>CAPTCHA Falhou!</b>\nPor favor, tente novamente.",
        "ru": "❌ <b>CAPTCHA Провалена!</b>\nПожалуйста, попробуйте снова.",
        "tr": "❌ <b>CAPTCHA Başarısız!</b>\nLütfen tekrar deneyin.",
        "id": "❌ <b>CAPTCHA Gagal!</b>\nSilakan coba lagi.",
        "de": "❌ <b>CAPTCHA Fehlgeschlagen!</b>\nBitte versuchen Sie es erneut.",
        "th": "❌ <b>CAPTCHA ล้มเหลว!</b>\nกรุณาลองอีกครั้ง",
    },
    "captcha_timeout": {
        "en": "⏰ <b>CAPTCHA Timeout</b>\nYou took too long to respond. Please try joining again.",
        "ar": "⏰ <b>انتهى وقت CAPTCHA</b>\nلقد استغرقت وقتًا طويلاً للرد. يرجى المحاولة مرة أخرى.",
        "es": "⏰ <b>Tiempo Agotado CAPTCHA</b>\nTardaste demasiado en responder. Intenta unirte de nuevo.",
        "fr": "⏰ <b>Délai CAPTCHA Dépassé</b>\nVous avez mis trop de temps à répondre. Veuillez réessayer.",
        "hi": "⏰ <b>CAPTCHA समय समाप्त</b>\nआपने जवाब देने में बहुत अधिक समय लिया। कृपया फिर से जुड़ने का प्रयास करें।",
        "pt": "⏰ <b>Tempo Esgotado CAPTCHA</b>\nVocê demorou muito para responder. Tente entrar novamente.",
        "ru": "⏰ <b>Время CAPTCHA Истекло</b>\nВы слишком долго отвечали. Пожалуйста, попробуйте присоединиться снова.",
        "tr": "⏰ <b>CAPTCHA Zaman Aşımı</b>\nYanıt vermek çok uzun sürdü. Lütfen tekrar katılmayı deneyin.",
        "id": "⏰ <b>Waktu Habis CAPTCHA</b>\nAnda terlalu lama merespons. Silakan coba bergabung lagi.",
        "de": "⏰ <b>CAPTCHA-Zeitüberschreitung</b>\nSie haben zu lange gebraucht zu antworten. Bitte versuchen Sie erneut beizutreten.",
        "th": "⏰ <b>หมดเวลา CAPTCHA</b>\nคุณใช้เวลานานเกินไป กรุณาลองเข้าร่วมอีกครั้ง",
    },
    # ============================================
    # TRUSTNET (FEDERATION)
    # ============================================
    "fed_ban_notice": {
        "en": "🌐 <b>Federation Ban Notice</b>\nUser {name} is banned in {federation}.\nReason: {reason}",
        "ar": "🌐 <b>إشعار حظر الاتحاد</b>\nالمستخدم {name} محظور في {federation}.\nالسبب: {reason}",
        "es": "🌐 <b>Aviso de Ban de Federación</b>\nEl usuario {name} está baneado en {federation}.\nRazón: {reason}",
        "fr": "🌐 <b>Avis de Ban de Fédération</b>\nL'utilisateur {name} est banni dans {federation}.\nRaison: {reason}",
        "hi": "🌐 <b>संघ प्रतिबंध सूचना</b>\nउपयोगकर्ता {name} {federation} में प्रतिबंधित है।\nकारण: {reason}",
        "pt": "🌐 <b>Aviso de Ban de Federação</b>\nO usuário {name} está banido em {federation}.\nMotivo: {reason}",
        "ru": "🌐 <b>Уведомление о Бане Федерации</b>\nПользователь {name} заблокирован в {federation}.\nПричина: {reason}",
        "tr": "🌐 <b>Federasyon Yasağı Bildirimi</b>\n{name} kullanıcısı {federation}'da yasaklı.\nSebep: {reason}",
        "id": "🌐 <b>Pemberitahuan Blokir Federasi</b>\nPengguna {name} diblokir di {federation}.\nAlasan: {reason}",
        "de": "🌐 <b>Föderations-Bann-Benachrichtigung</b>\nBenutzer {name} ist in {federation} gebannt.\nGrund: {reason}",
        "th": "🌐 <b>การแจ้งเตือนการแบนสหพันธ์</b>\nผู้ใช้ {name} ถูกแบนใน {federation}\nเหตุผล: {reason}",
    },
    "trust_score_label": {
        "en": "🛡️ Trust Score: {score}/100",
        "ar": "🛡️ درجة الثقة: {score}/100",
        "es": "🛡️ Puntuación de Confianza: {score}/100",
        "fr": "🛡️ Score de Confiance: {score}/100",
        "hi": "🛡️ ट्रस्ट स्कोर: {score}/100",
        "pt": "🛡️ Pontuação de Confiança: {score}/100",
        "ru": "🛡️ Рейтинг Доверия: {score}/100",
        "tr": "🛡️ Güven Puanı: {score}/100",
        "id": "🛡️ Skor Kepercayaan: {score}/100",
        "de": "🛡️ Vertrauenswert: {score}/100",
        "th": "🛡️ คะแนนความน่าเชื่อถือ: {score}/100",
    },
    # ============================================
    # NIGHT MODE
    # ============================================
    "night_mode_on": {
        "en": "🌙 <b>Night Mode Activated</b>\nGroup is now in restricted mode until {end_time}.",
        "ar": "🌙 <b>تم تفعيل الوضع الليلي</b>\nالمجموعة في الوضع المقيد الآن حتى {end_time}.",
        "es": "🌙 <b>Modo Nocturno Activado</b>\nEl grupo está en modo restringido hasta {end_time}.",
        "fr": "🌙 <b>Mode Nuit Activé</b>\nLe groupe est en mode restreint jusqu'à {end_time}.",
        "hi": "🌙 <b>नाइट मोड सक्रिय</b>\nसमूह अब प्रतिबंधित मोड में है {end_time} तक।",
        "pt": "🌙 <b>Modo Noturno Ativado</b>\nO grupo está em modo restrito até {end_time}.",
        "ru": "🌙 <b>Ночной Режим Активирован</b>\nГруппа в ограниченном режиме до {end_time}.",
        "tr": "🌙 <b>Gece Modu Etkinleştirildi</b>\nGrup, {end_time} kadar kısıtlı modda.",
        "id": "🌙 <b>Mode Malam Diaktifkan</b>\nGrup dalam mode terbatas sampai {end_time}.",
        "de": "🌙 <b>Nachtmodus Aktiviert</b>\nGruppe ist bis {end_time} im eingeschränkten Modus.",
        "th": "🌙 <b>เปิดใช้งานโหมดกลางคืน</b>\nกลุ่มอยู่ในโหมดจำกัดจนถึง {end_time}",
    },
    "night_mode_off": {
        "en": "☀️ <b>Night Mode Deactivated</b>\nGroup permissions restored. Good morning!",
        "ar": "☀️ <b>تم إلغاء تنشيط الوضع الليلي</b>\nتمت استعادة أذونات المجموعة. صباح الخير!",
        "es": "☀️ <b>Modo Nocturno Desactivado</b>\nPermisos del grupo restaurados. ¡Buenos días!",
        "fr": "☀️ <b>Mode Nuit Désactivé</b>\nPermissions du groupe restaurées. Bonjour !",
        "hi": "☀️ <b>नाइट मोड निष्क्रिय</b>\nसमूह की अनुमतियाँ बहाल की गईं। शुभ प्रभात!",
        "pt": "☀️ <b>Modo Noturno Desativado</b>\nPermissões do grupo restauradas. Bom dia!",
        "ru": "☀️ <b>Ночной Режим Отключён</b>\nПрава группы восстановлены. Доброе утро!",
        "tr": "☀️ <b>Gece Modu Devre Dışı</b>\nGrup izinleri geri yüklendi. Günaydın!",
        "id": "☀️ <b>Mode Malam Dinonaktifkan</b>\nIzin grup dipulihkan. Selamat pagi!",
        "de": "☀️ <b>Nachtmodus Deaktiviert</b>\nGruppenberechtigungen wiederhergestellt. Guten Morgen!",
        "th": "☀️ <b>ปิดใช้งานโหมดกลางคืน</b>\nสิทธิ์กลุ่มได้รับการคืนค่า สวัสดีตอนเช้า!",
    },
    "morning": {
        "en": "Good morning! The group is now open.",
        "ar": "صباح الخير! المجموعة مفتوحة الآن.",
        "es": "¡Buenos días! El grupo está abierto ahora.",
        "fr": "Bonjour ! Le groupe est maintenant ouvert.",
        "hi": "शुभ प्रभात! समूह अब खुला है।",
        "pt": "Bom dia! O grupo está aberto agora.",
        "ru": "Доброе утро! Группа теперь открыта.",
        "tr": "Günaydın! Grup şimdi açık.",
        "id": "Selamat pagi! Grup sekarang terbuka.",
        "de": "Guten Morgen! Die Gruppe ist jetzt offen.",
        "th": "สวัสดีตอนเช้า! กลุ่มเปิดแล้ว",
    },
    # ============================================
    # COMMUNITY VOTE
    # ============================================
    "vote_started": {
        "en": "⚖️ <b>Community Vote Started</b>\nTarget: {user}\nReason: {reason}\nVote with the buttons below.\nThreshold: {threshold} votes | Timeout: {timeout} min",
        "ar": "⚖️ <b>بدأ التصويت المجتمعي</b>\nالهدف: {user}\nالسبب: {reason}\nصوت باستخدام الأزرار أدناه.\nالحد: {threshold} أصوات | المهلة: {timeout} دقيقة",
        "es": "⚖️ <b>Votación Comunitaria Iniciada</b>\nObjetivo: {user}\nRazón: {reason}\nVota con los botones de abajo.\nUmbral: {threshold} votos | Tiempo: {timeout} min",
        "fr": "⚖️ <b>Vote Communautaire Commencé</b>\nCible: {user}\nRaison: {reason}\nVotez avec les boutons ci-dessous.\nSeuil: {threshold} votes | Délai: {timeout} min",
        "hi": "⚖️ <b>सामुदायिक मतदान शुरू</b>\nलक्ष्य: {user}\nकारण: {reason}\nनीचे दिए गए बटनों से मतदान करें।\nसीमा: {threshold} वोट | समय सीमा: {timeout} मिनट",
        "pt": "⚖️ <b>Votação da Comunidade Iniciada</b>\nAlvo: {user}\nMotivo: {reason}\nVote com os botões abaixo.\nLimite: {threshold} votos | Tempo: {timeout} min",
        "ru": "⚖️ <b>Началось Общественное Голосование</b>\nЦель: {user}\nПричина: {reason}\nГолосуйте кнопками ниже.\nПорог: {threshold} голосов | Таймаут: {timeout} мин",
        "tr": "⚖️ <b>Topluluk Oylaması Başladı</b>\nHedef: {user}\nSebep: {reason}\nAşağıdaki butonlarla oy verin.\nEşik: {threshold} oy | Süre: {timeout} dk",
        "id": "⚖️ <b>Pemungutan Suara Komunitas Dimulai</b>\nTarget: {user}\nAlasan: {reason}\nPilih dengan tombol di bawah.\nAmbang: {threshold} suara | Batas: {timeout} menit",
        "de": "⚖️ <b>Community-Abstimmung Gestartet</b>\nZiel: {user}\nGrund: {reason}\nStimmen Sie mit den Buttons unten ab.\nSchwelle: {threshold} Stimmen | Zeitlimit: {timeout} min",
        "th": "⚖️ <b>เริ่มการโหวตชุมชน</b>\nเป้าหมาย: {user}\nเหตุผล: {reason}\nโหวตด้วยปุ่มด้านล่าง\nเกณฑ์: {threshold} โหวต | หมดเวลา: {timeout} นาที",
    },
    "vote_passed": {
        "en": "✅ <b>Vote Passed</b>\nThe community has decided.\nAction: {action}",
        "ar": "✅ <b>تم التصويت</b>\nقررت المجتمع.\nالإجراء: {action}",
        "es": "✅ <b>Voto Aprobado</b>\nLa comunidad ha decidido.\nAcción: {action}",
        "fr": "✅ <b>Vote Adopté</b>\nLa communauté a décidé.\nAction: {action}",
        "hi": "✅ <b>मतदान पारित</b>\nसमुदाय ने निर्णय लिया है।\nकार्रवाई: {action}",
        "pt": "✅ <b>Votação Aprovada</b>\nA comunidade decidiu.\nAção: {action}",
        "ru": "✅ <b>Голосование Пройдено</b>\nСообщество приняло решение.\nДействие: {action}",
        "tr": "✅ <b>Oylama Kabul Edildi</b>\nTopluluk karar verdi.\nEylem: {action}",
        "id": "✅ <b>Pemungutan Suara Diterima</b>\nKomunitas telah memutuskan.\nTindakan: {action}",
        "de": "✅ <b>Abstimmung Bestanden</b>\nDie Community hat entschieden.\nAktion: {action}",
        "th": "✅ <b>ผ่านการโหวต</b>\nชุมชนตัดสินใจแล้ว\nการกระทำ: {action}",
    },
    "vote_failed": {
        "en": "❌ <b>Vote Failed</b>\nNot enough votes. The user stays.",
        "ar": "❌ <b>فشل التصويت</b>\nلم يكن هناك أصوات كافية. يبقى المستخدم.",
        "es": "❌ <b>Votación Fallida</b>\nNo suficientes votos. El usuario se queda.",
        "fr": "❌ <b>Vote Échoué</b>\nPas assez de votes. L'utilisateur reste.",
        "hi": "❌ <b>मतदान विफल</b>\nपर्याप्त वोट नहीं। उपयोगकर्ता रहता है।",
        "pt": "❌ <b>Votação Falhou</b>\nVotos insuficientes. O usuário fica.",
        "ru": "❌ <b>Голосование Провалено</b>\nНедостаточно голосов. Пользователь остаётся.",
        "tr": "❌ <b>Oylama Başarısız</b>\nYeterli oy yok. Kullanıcı kalıyor.",
        "id": "❌ <b>Pemungutan Suara Gagal</b>\nTidak cukup suara. Pengguna tetap.",
        "de": "❌ <b>Abstimmung Fehlgeschlagen</b>\nNicht genug Stimmen. Der Benutzer bleibt.",
        "th": "❌ <b>การโหวตล้มเหลว</b>\nโหวตไม่เพียงพอ ผู้ใช้ยังคงอยู่",
    },
    # ============================================
    # RULES / NOTES
    # ============================================
    "rules_header": {
        "en": "📋 <b>Group Rules</b>",
        "ar": "📋 <b>قواعد المجموعة</b>",
        "es": "📋 <b>Reglas del Grupo</b>",
        "fr": "📋 <b>Règles du Groupe</b>",
        "hi": "📋 <b>समूह के नियम</b>",
        "pt": "📋 <b>Regras do Grupo</b>",
        "ru": "📋 <b>Правила Группы</b>",
        "tr": "📋 <b>Grup Kuralları</b>",
        "id": "📋 <b>Aturan Grup</b>",
        "de": "📋 <b>Gruppenregeln</b>",
        "th": "📋 <b>กฎของกลุ่ม</b>",
    },
    "no_rules": {
        "en": "📋 No rules have been set for this group yet.",
        "ar": "📋 لم يتم تعيين قواعد لهذه المجموعة بعد.",
        "es": "📋 Aún no se han establecido reglas para este grupo.",
        "fr": "📋 Aucune règle n'a encore été définie pour ce groupe.",
        "hi": "📋 इस समूह के लिए अभी तक कोई नियम निर्धारित नहीं किए गए हैं।",
        "pt": "📋 Nenhuma regra foi definida para este grupo ainda.",
        "ru": "📋 Для этой группы ещё не установлены правила.",
        "tr": "📋 Bu grup için henüz kural belirlenmemiş.",
        "id": "📋 Belum ada aturan yang ditetapkan untuk grup ini.",
        "de": "📋 Für diese Gruppe wurden noch keine Regeln festgelegt.",
        "th": "📋 ยังไม่มีกฎสำหรับกลุ่มนี้",
    },
    # ============================================
    # LANGUAGE SETTINGS
    # ============================================
    "lang_set": {
        "en": "✅ Your language has been set to {lang}.",
        "ar": "✅ تم تعيين لغتك إلى {lang}.",
        "es": "✅ Tu idioma ha sido configurado a {lang}.",
        "fr": "✅ Votre langue a été définie sur {lang}.",
        "hi": "✅ आपकी भाषा {lang} पर सेट कर दी गई है।",
        "pt": "✅ Seu idioma foi configurado para {lang}.",
        "ru": "✅ Ваш язык установлен на {lang}.",
        "tr": "✅ Diliniz {lang} olarak ayarlandı.",
        "id": "✅ Bahasa Anda telah diatur ke {lang}.",
        "de": "✅ Ihre Sprache wurde auf {lang} gesetzt.",
        "th": "✅ ตั้งค่าภาษาของคุณเป็น {lang}",
    },
    "grouplang_set": {
        "en": "✅ Group language has been set to {lang}.",
        "ar": "✅ تم تعيين لغة المجموعة إلى {lang}.",
        "es": "✅ El idioma del grupo ha sido configurado a {lang}.",
        "fr": "✅ La langue du groupe a été définie sur {lang}.",
        "hi": "✅ समूह की भाषा {lang} पर सेट कर दी गई है।",
        "pt": "✅ O idioma do grupo foi configurado para {lang}.",
        "ru": "✅ Язык группы установлен на {lang}.",
        "tr": "✅ Grup dili {lang} olarak ayarlandı.",
        "id": "✅ Bahasa grup telah diatur ke {lang}.",
        "de": "✅ Gruppensprache wurde auf {lang} gesetzt.",
        "th": "✅ ตั้งค่าภาษากลุ่มเป็น {lang}",
    },
    # ============================================
    # GENERAL ERRORS / SUCCESS
    # ============================================
    "not_admin": {
        "en": "❌ You must be an admin to use this command.",
        "ar": "❌ يجب أن تكون مسؤولاً لاستخدام هذا الأمر.",
        "es": "❌ Debes ser administrador para usar este comando.",
        "fr": "❌ Vous devez être administrateur pour utiliser cette commande.",
        "hi": "❌ इस कमांड का उपयोग करने के लिए आपको व्यवस्थापक होना चाहिए।",
        "pt": "❌ Você deve ser um administrador para usar este comando.",
        "ru": "❌ Вы должны быть администратором, чтобы использовать эту команду.",
        "tr": "❌ Bu komutu kullanmak için yönetici olmalısınız.",
        "id": "❌ Anda harus menjadi admin untuk menggunakan perintah ini.",
        "de": "❌ Sie müssen Administrator sein, um diesen Befehl zu verwenden.",
        "th": "❌ คุณต้องเป็นผู้ดูแลระบบเพื่อใช้คำสั่งนี้",
    },
    "no_reply": {
        "en": "❌ Please reply to a message to use this command.",
        "ar": "❌ يرجى الرد على رسالة لاستخدام هذا الأمر.",
        "es": "❌ Por favor responde a un mensaje para usar este comando.",
        "fr": "❌ Veuillez répondre à un message pour utiliser cette commande.",
        "hi": "❌ इस कमांड का उपयोग करने के लिए कृपया एक संदेश का उत्तर दें।",
        "pt": "❌ Por favor, responda a uma mensagem para usar este comando.",
        "ru": "❌ Пожалуйста, ответьте на сообщение, чтобы использовать эту команду.",
        "tr": "❌ Bu komutu kullanmak için lütfen bir mesaja yanıt verin.",
        "id": "❌ Silakan balas pesan untuk menggunakan perintah ini.",
        "de": "❌ Bitte antworten Sie auf eine Nachricht, um diesen Befehl zu verwenden.",
        "th": "❌ กรุณาตอบกลับข้อความเพื่อใช้คำสั่งนี้",
    },
    "groups_only": {
        "en": "❌ This command only works in groups.",
        "ar": "❌ هذا الأمر يعمل فقط في المجموعات.",
        "es": "❌ Este comando solo funciona en grupos.",
        "fr": "❌ Cette commande fonctionne uniquement dans les groupes.",
        "hi": "❌ यह कमांड केवल समूहों में काम करता है।",
        "pt": "❌ Este comando funciona apenas em grupos.",
        "ru": "❌ Эта команда работает только в группах.",
        "tr": "❌ Bu komut yalnızca gruplarda çalışır.",
        "id": "❌ Perintah ini hanya berfungsi di grup.",
        "de": "❌ Dieser Befehl funktioniert nur in Gruppen.",
        "th": "❌ คำสั่งนี้ใช้ได้เฉพาะในกลุ่ม",
    },
    "generic_error": {
        "en": "❌ An error occurred. Please try again later.",
        "ar": "❌ حدث خطأ. يرجى المحاولة مرة أخرى لاحقاً.",
        "es": "❌ Ocurrió un error. Por favor intenta de nuevo más tarde.",
        "fr": "❌ Une erreur s'est produite. Veuillez réessayer plus tard.",
        "hi": "❌ एक त्रुटि हुई। कृपया बाद में पुनः प्रयास करें।",
        "pt": "❌ Ocorreu um erro. Por favor, tente novamente mais tarde.",
        "ru": "❌ Произошла ошибка. Пожалуйста, попробуйте позже.",
        "tr": "❌ Bir hata oluştu. Lütfen daha sonra tekrar deneyin.",
        "id": "❌ Terjadi kesalahan. Silakan coba lagi nanti.",
        "de": "❌ Ein Fehler ist aufgetreten. Bitte versuchen Sie es später erneut.",
        "th": "❌ เกิดข้อผิดพลาด กรุณาลองอีกครั้งในภายหลัง",
    },
    "success": {
        "en": "✅ Done!",
        "ar": "✅ تم!",
        "es": "✅ ¡Hecho!",
        "fr": "✅ Fait!",
        "hi": "✅ हो गया!",
        "pt": "✅ Feito!",
        "ru": "✅ Готово!",
        "tr": "✅ Tamamlandı!",
        "id": "✅ Selesai!",
        "de": "✅ Erledigt!",
        "th": "✅ เสร็จสิ้น!",
    },
    # ============================================
    # SYNC COMMAND
    # ============================================
    "sync_success": {
        "en": "✅ Group synced successfully!",
        "ar": "��� تمت مزامنة المجموعة بنجاح!",
        "es": "✅ ¡Grupo sincronizado exitosamente!",
        "fr": "✅ Groupe synchronisé avec succès!",
        "hi": "✅ समूह सफलतापूर्वक सिंक किया गया!",
        "pt": "✅ Grupo sincronizado com sucesso!",
        "ru": "✅ Группа успешно синхронизирована!",
        "tr": "✅ Grup başarıyla senkronize edildi!",
        "id": "✅ Grup berhasil disinkronkan!",
        "de": "✅ Gruppe erfolgreich synchronisiert!",
        "th": "✅ ซิงค์กลุ่มสำเร็จ!",
    },
    # ============================================
    # NAVIGATION LABELS (v21)
    # ============================================
    "nav_dashboard": {
        "en": "Dashboard",
        "ar": "لوحة التحكم",
        "es": "Panel de control",
        "fr": "Tableau de bord",
        "hi": "डैशबोर्ड",
        "pt": "Painel",
        "ru": "Панель управления",
        "tr": "Panel",
        "id": "Dasbor",
        "de": "Dashboard",
        "th": "แดชบอร์ด",
    },
    "nav_bots": {
        "en": "Bots",
        "ar": "البوتات",
        "es": "Bots",
        "fr": "Bots",
        "hi": "बॉट्स",
        "pt": "Bots",
        "ru": "Боты",
        "tr": "Botlar",
        "id": "Bot",
        "de": "Bots",
        "th": "บอท",
    },
    "nav_moderation": {
        "en": "Moderation",
        "ar": "الإشراف",
        "es": "Moderación",
        "fr": "Modération",
        "hi": "मॉडरेशन",
        "pt": "Moderação",
        "ru": "Модерация",
        "tr": "Moderasyon",
        "id": "Moderasi",
        "de": "Moderation",
        "th": "การจัดการ",
    },
    "nav_automod": {
        "en": "AutoMod",
        "ar": "الفل الآلي",
        "es": "AutoMod",
        "fr": "AutoMod",
        "hi": "ऑटोमॉड",
        "pt": "AutoMod",
        "ru": "АвтоМод",
        "tr": "AutoMod",
        "id": "AutoMod",
        "de": "AutoMod",
        "th": "ระบบจัดการอัตโนมัติ",
    },
    "nav_members": {
        "en": "Members",
        "ar": "الأعضاء",
        "es": "Miembros",
        "fr": "Membres",
        "hi": "सदस्य",
        "pt": "Membros",
        "ru": "Участники",
        "tr": "Üyeler",
        "id": "Anggota",
        "de": "Mitglieder",
        "th": "สมาชิก",
    },
    "nav_analytics": {
        "en": "Analytics",
        "ar": "التحليلات",
        "es": "Análisis",
        "fr": "Analytique",
        "hi": "विश्लेषण",
        "pt": "Análises",
        "ru": "Аналитика",
        "tr": "Analitik",
        "id": "Analitik",
        "de": "Analytik",
        "th": "การวิเคราะห์",
    },
    "nav_broadcast": {
        "en": "Broadcast",
        "ar": "البث",
        "es": "Difusión",
        "fr": "Diffusion",
        "hi": "प्रसारण",
        "pt": "Transmissão",
        "ru": "Рассылка",
        "tr": "Yayın",
        "id": "Siaran",
        "de": "Broadcast",
        "th": "การประกาศ",
    },
    "nav_reports": {
        "en": "Reports",
        "ar": "التقارير",
        "es": "Informes",
        "fr": "Rapports",
        "hi": "रिपोर्ट",
        "pt": "Relatórios",
        "ru": "Отчёты",
        "tr": "Raporlar",
        "th": "รายงาน",
        "id": "Laporan",
        "de": "Berichte",
    },
    "nav_greetings": {
        "en": "Greetings",
        "ar": "الترحيب",
        "es": "Saludos",
        "fr": "Accueils",
        "hi": "स्वागत",
        "pt": "Saudações",
        "ru": "Приветствия",
        "tr": "Karşılama",
        "id": "Salam",
        "de": "Begrüßungen",
        "th": "การต้อนรับ",
    },
    "nav_antiraid": {
        "en": "Anti-Raid",
        "ar": "مضاد الغارات",
        "es": "Anti-Raid",
        "fr": "Anti-Raid",
        "hi": "एंटी-रेड",
        "pt": "Anti-Raid",
        "ru": "Анти-рейд",
        "tr": "Anti-Raid",
        "id": "Anti-Raid",
        "de": "Anti-Raid",
        "th": "ป้องกันการโจมตี",
    },
    "nav_settings": {
        "en": "Settings",
        "ar": "الإعدادات",
        "es": "Configuración",
        "fr": "Paramètres",
        "hi": "सेटिंग्स",
        "pt": "Configurações",
        "ru": "Настройки",
        "tr": "Ayarlar",
        "id": "Pengaturan",
        "de": "Einstellungen",
        "th": "การตั้งค่า",
    },
    "nav_logs": {
        "en": "Logs",
        "ar": "السجلات",
        "es": "Registros",
        "fr": "Journaux",
        "hi": "लॉग",
        "pt": "Logs",
        "ru": "Логи",
        "tr": "Kayıtlar",
        "id": "Log",
        "de": "Protokolle",
        "th": "บันทึก",
    },
    "nav_roles": {
        "en": "Roles",
        "ar": "الأدوار",
        "es": "Roles",
        "fr": "Rôles",
        "hi": "भूमिकाएं",
        "pt": "Funções",
        "ru": "Роли",
        "tr": "Roller",
        "id": "Peran",
        "de": "Rollen",
        "th": "บทบาท",
    },
    "nav_notes": {
        "en": "Notes",
        "ar": "الملاحظات",
        "es": "Notas",
        "fr": "Notes",
        "hi": "नोट्स",
        "pt": "Notas",
        "ru": "Заметки",
        "tr": "Notlar",
        "id": "Catatan",
        "de": "Notizen",
        "th": "บันทึกย่อ",
    },
    "nav_xp": {
        "en": "XP & Levels",
        "ar": "نقاط الخبرة",
        "es": "XP y Niveles",
        "fr": "XP et Niveaux",
        "hi": "XP और लेवल",
        "pt": "XP e Níveis",
        "ru": "Опыт и уровни",
        "tr": "XP ve Seviye",
        "id": "XP dan Level",
        "de": "XP und Level",
        "th": "คะแนนและระดับ",
    },
    "nav_owner": {
        "en": "Owner",
        "ar": "المالك",
        "es": "Propietario",
        "fr": "Propriétaire",
        "hi": "मालिक",
        "pt": "Proprietário",
        "ru": "Владелец",
        "tr": "Sahip",
        "id": "Pemilik",
        "de": "Eigentümer",
        "th": "เจ้าของ",
    },
    # ============================================
    # NAVIGATION LABELS v21 (NEW)
    # ============================================
    "nav_trustnet": {
        "en": "TrustNet",
        "ar": "شبكة الثقة",
        "es": "Red de Confianza",
        "fr": "Réseau de Confiance",
        "hi": "ट्रस्टनेट",
        "pt": "Rede de Confiança",
        "ru": "Сеть доверия",
        "tr": "Güven Ağı",
        "id": "Jaringan Kepercayaan",
        "de": "Vertrauensnetz",
        "th": "เครือข่ายความน่าเชื่อถือ",
    },
    "nav_captcha": {
        "en": "Captcha",
        "ar": "الكابتشا",
        "es": "Captcha",
        "fr": "Captcha",
        "hi": "कैप्चा",
        "pt": "Captcha",
        "ru": "Капча",
        "tr": "Captcha",
        "id": "Captcha",
        "de": "Captcha",
        "th": "แคปช่า",
    },
    "nav_community_vote": {
        "en": "Community Vote",
        "ar": "تصويت المجتمع",
        "es": "Votación Comunitaria",
        "fr": "Vote Communautaire",
        "hi": "सामुदायिक मतदान",
        "pt": "Votação Comunitária",
        "ru": "Общественное голосование",
        "tr": "Topluluk Oylaması",
        "id": "Pemungutan Suara Komunitas",
        "de": "Community-Abstimmung",
        "th": "การโหวตชุมชน",
    },
    "nav_night_mode": {
        "en": "Night Mode",
        "ar": "الوضع الليلي",
        "es": "Modo Nocturno",
        "fr": "Mode Nuit",
        "hi": "नाइट मोड",
        "pt": "Modo Noturno",
        "ru": "Ночной режим",
        "tr": "Gece Modu",
        "id": "Mode Malam",
        "de": "Nachtmodus",
        "th": "โหมดกลางคืน",
    },
    "nav_history": {
        "en": "Name History",
        "ar": "سجل الأسماء",
        "es": "Historial de Nombres",
        "fr": "Historique des Noms",
        "hi": "नाम इतिहास",
        "pt": "Histórico de Nomes",
        "ru": "История имён",
        "tr": "İsim Geçmişi",
        "id": "Riwayat Nama",
        "de": "Namensverlauf",
        "th": "ประวัติชื่อ",
    },
    "nav_language": {
        "en": "Language",
        "ar": "اللغة",
        "es": "Idioma",
        "fr": "Langue",
        "hi": "भाषा",
        "pt": "Idioma",
        "ru": "Язык",
        "tr": "Dil",
        "id": "Bahasa",
        "de": "Sprache",
        "th": "ภาษา",
    },
    "nav_persona": {
        "en": "Bot Persona",
        "ar": "شخصية البوت",
        "es": "Personalidad del Bot",
        "fr": "Personnalité du Bot",
        "hi": "बॉट पर्सोना",
        "pt": "Personalidade do Bot",
        "ru": "Персона бота",
        "tr": "Bot Kişiliği",
        "id": "Persona Bot",
        "de": "Bot-Persönlichkeit",
        "th": "บุคลิกบอท",
    },
    # ============================================
    # BUTTON LABELS
    # ============================================
    "save_btn": {
        "en": "Save",
        "ar": "حفظ",
        "es": "Guardar",
        "fr": "Enregistrer",
        "hi": "सहेजें",
        "pt": "Salvar",
        "ru": "Сохранить",
        "tr": "Kaydet",
        "id": "Simpan",
        "de": "Speichern",
        "th": "บันทึก",
    },
    "cancel_btn": {
        "en": "Cancel",
        "ar": "إلغاء",
        "es": "Cancelar",
        "fr": "Annuler",
        "hi": "रद्द करें",
        "pt": "Cancelar",
        "ru": "Отмена",
        "tr": "İptal",
        "id": "Batal",
        "de": "Abbrechen",
        "th": "ยกเลิก",
    },
    "enable_label": {
        "en": "Enable",
        "ar": "تفعيل",
        "es": "Activar",
        "fr": "Activer",
        "hi": "सक्षम करें",
        "pt": "Ativar",
        "ru": "Включить",
        "tr": "Etkinleştir",
        "id": "Aktifkan",
        "de": "Aktivieren",
        "th": "เปิดใช้งาน",
    },
    "disable_label": {
        "en": "Disable",
        "ar": "تعطيل",
        "es": "Desactivar",
        "fr": "Désactiver",
        "hi": "अक्षम करें",
        "pt": "Desativar",
        "ru": "Отключить",
        "tr": "Devre Dışı Bırak",
        "id": "Nonaktifkan",
        "de": "Deaktivieren",
        "th": "ปิดใช้งาน",
    },
    "delete": {
        "en": "Delete",
        "ar": "حذف",
        "es": "Eliminar",
        "fr": "Supprimer",
        "hi": "हटाएं",
        "pt": "Excluir",
        "ru": "Удалить",
        "tr": "Sil",
        "id": "Hapus",
        "de": "Löschen",
        "th": "ลบ",
    },
    "edit": {
        "en": "Edit",
        "ar": "تعديل",
        "es": "Editar",
        "fr": "Modifier",
        "hi": "संपादित करें",
        "pt": "Editar",
        "ru": "Редактировать",
        "tr": "Düzenle",
        "id": "Edit",
        "de": "Bearbeiten",
        "th": "แก้ไข",
    },
    "confirm": {
        "en": "Confirm",
        "ar": "تأكيد",
        "es": "Confirmar",
        "fr": "Confirmer",
        "hi": "पुष्टि करें",
        "pt": "Confirmar",
        "ru": "Подтвердить",
        "tr": "Onayla",
        "id": "Konfirmasi",
        "de": "Bestätigen",
        "th": "ยืนยัน",
    },
    "close": {
        "en": "Close",
        "ar": "إغلاق",
        "es": "Cerrar",
        "fr": "Fermer",
        "hi": "बंद करें",
        "pt": "Fechar",
        "ru": "Закрыть",
        "tr": "Kapat",
        "id": "Tutup",
        "de": "Schließen",
        "th": "ปิด",
    },
    "refresh": {
        "en": "Refresh",
        "ar": "تحديث",
        "es": "Actualizar",
        "fr": "Actualiser",
        "hi": "रिफ्रेश करें",
        "pt": "Atualizar",
        "ru": "Обновить",
        "tr": "Yenile",
        "id": "Segarkan",
        "de": "Aktualisieren",
        "th": "รีเฟรช",
    },
    "search": {
        "en": "Search",
        "ar": "بحث",
        "es": "Buscar",
        "fr": "Rechercher",
        "hi": "खोजें",
        "pt": "Buscar",
        "ru": "Поиск",
        "tr": "Ara",
        "id": "Cari",
        "de": "Suchen",
        "th": "ค้นหา",
    },
    "copy": {
        "en": "Copy",
        "ar": "نسخ",
        "es": "Copiar",
        "fr": "Copier",
        "hi": "कॉपी करें",
        "pt": "Copiar",
        "ru": "Копировать",
        "tr": "Kopyala",
        "id": "Salin",
        "de": "Kopieren",
        "th": "คัดลอก",
    },
    "copied": {
        "en": "Copied!",
        "ar": "تم النسخ!",
        "es": "¡Copiado!",
        "fr": "Copié!",
        "hi": "कॉपी हो गया!",
        "pt": "Copiado!",
        "ru": "Скопировано!",
        "tr": "Kopyalandı!",
        "id": "Disalin!",
        "de": "Kopiert!",
        "th": "คัดลอกแล้ว!",
    },
    "reset": {
        "en": "Reset",
        "ar": "إعادة تعيين",
        "es": "Restablecer",
        "fr": "Réinitialiser",
        "hi": "रीसेट करें",
        "pt": "Redefinir",
        "ru": "Сбросить",
        "tr": "Sıfırla",
        "id": "Atur Ulang",
        "de": "Zurücksetzen",
        "th": "รีเซ็ต",
    },
    "add_bot": {
        "en": "Add Bot",
        "ar": "إضافة بوت",
        "es": "Agregar Bot",
        "fr": "Ajouter un Bot",
        "hi": "बॉट जोड़ें",
        "pt": "Adicionar Bot",
        "ru": "Добавить бота",
        "tr": "Bot Ekle",
        "id": "Tambah Bot",
        "de": "Bot hinzufügen",
        "th": "เพิ่มบอท",
    },
    "add_clone": {
        "en": "Add Clone",
        "ar": "إضافة نسخة",
        "es": "Agregar Clon",
        "fr": "Ajouter un Clone",
        "hi": "क्लोन जोड़ें",
        "pt": "Adicionar Clone",
        "ru": "Добавить клон",
        "tr": "Klon Ekle",
        "id": "Tambah Klon",
        "de": "Klon hinzufügen",
        "th": "เพิ่มโคลน",
    },
    # ============================================
    # STATUS LABELS
    # ============================================
    "status_active": {
        "en": "Active",
        "ar": "نشط",
        "es": "Activo",
        "fr": "Actif",
        "hi": "सक्रिय",
        "pt": "Ativo",
        "ru": "Активен",
        "tr": "Aktif",
        "id": "Aktif",
        "de": "Aktiv",
        "th": "ใช้งาน",
    },
    "status_inactive": {
        "en": "Inactive",
        "ar": "غير نشط",
        "es": "Inactivo",
        "fr": "Inactif",
        "hi": "निष्क्रिय",
        "pt": "Inativo",
        "ru": "Неактивен",
        "tr": "Pasif",
        "id": "Tidak Aktif",
        "de": "Inaktiv",
        "th": "ไม่ใช้งาน",
    },
    "status_pending": {
        "en": "Pending",
        "ar": "معلق",
        "es": "Pendiente",
        "fr": "En attente",
        "hi": "लंबित",
        "pt": "Pendente",
        "ru": "Ожидание",
        "tr": "Beklemede",
        "id": "Tertunda",
        "de": "Ausstehend",
        "th": "รอดำเนินการ",
    },
    "status_online": {
        "en": "Online",
        "ar": "متصل",
        "es": "En línea",
        "fr": "En ligne",
        "hi": "ऑनलाइन",
        "pt": "Online",
        "ru": "Онлайн",
        "tr": "Çevrimiçi",
        "id": "Online",
        "de": "Online",
        "th": "ออนไลน์",
    },
    "status_offline": {
        "en": "Offline",
        "ar": "غير متصل",
        "es": "Desconectado",
        "fr": "Hors ligne",
        "hi": "ऑफलाइन",
        "pt": "Offline",
        "ru": "Офлайн",
        "tr": "Çevrimdışı",
        "id": "Offline",
        "de": "Offline",
        "th": "ออฟไลน์",
    },
    "status_live": {
        "en": "Live",
        "ar": "مباشر",
        "es": "En vivo",
        "fr": "En direct",
        "hi": "लाइव",
        "pt": "Ao vivo",
        "ru": "В эфире",
        "tr": "Canlı",
        "id": "Langsung",
        "de": "Live",
        "th": "ถ่ายทอดสด",
    },
    # ============================================
    # MODERATION LABELS
    # ============================================
    "action_ban": {
        "en": "Ban",
        "ar": "حظر",
        "es": "Banear",
        "fr": "Bannir",
        "hi": "बैन करें",
        "pt": "Banir",
        "ru": "Забанить",
        "tr": "Yasakla",
        "id": "Blokir",
        "de": "Bannen",
        "th": "แบน",
    },
    "action_kick": {
        "en": "Kick",
        "ar": "طرد",
        "es": "Expulsar",
        "fr": "Expulser",
        "hi": "निकालें",
        "pt": "Expulsar",
        "ru": "Исключить",
        "tr": "At",
        "id": "Tendang",
        "de": "Entfernen",
        "th": "เตะ",
    },
    "action_mute": {
        "en": "Mute",
        "ar": "كتم",
        "es": "Silenciar",
        "fr": "Muet",
        "hi": "म्यूट करें",
        "pt": "Mutar",
        "ru": "Заглушить",
        "tr": "Sustur",
        "id": "Bisukan",
        "de": "Stummschalten",
        "th": "ปิดเสียง",
    },
    "action_warn": {
        "en": "Warn",
        "ar": "تحذير",
        "es": "Advertir",
        "fr": "Avertir",
        "hi": "चेतावनी दें",
        "pt": "Avisar",
        "ru": "Предупредить",
        "tr": "Uyar",
        "id": "Peringatkan",
        "de": "Verwarnen",
        "th": "เตือน",
    },
    "action_delete": {
        "en": "Delete",
        "ar": "حذف",
        "es": "Eliminar",
        "fr": "Supprimer",
        "hi": "हटाएं",
        "pt": "Excluir",
        "ru": "Удалить",
        "tr": "Sil",
        "id": "Hapus",
        "de": "Löschen",
        "th": "ลบ",
    },
    # ============================================
    # AUTOMOD LABELS
    # ============================================
    "antiflood": {
        "en": "Anti-Flood",
        "ar": "مضاد الكتابة",
        "es": "Anti-Inundación",
        "fr": "Anti-Flood",
        "hi": "एंटी-फ्लड",
        "pt": "Anti-Flood",
        "ru": "Анти-флуд",
        "tr": "Anti-Flood",
        "id": "Anti-Flood",
        "de": "Anti-Flood",
        "th": "ป้องกันสแปม",
    },
    "antilink": {
        "en": "Anti-Link",
        "ar": "مضاد الروابط",
        "es": "Anti-Enlace",
        "fr": "Anti-Lien",
        "hi": "एंटी-लिंक",
        "pt": "Anti-Link",
        "ru": "Анти-ссылка",
        "tr": "Anti-Link",
        "id": "Anti-Link",
        "de": "Anti-Link",
        "th": "ป้องกันลิงก์",
    },
    "antispam": {
        "en": "Anti-Spam",
        "ar": "مضاد الرسائل",
        "es": "Anti-Spam",
        "fr": "Anti-Spam",
        "hi": "एंटी-स्पैम",
        "pt": "Anti-Spam",
        "ru": "Анти-спам",
        "tr": "Anti-Spam",
        "id": "Anti-Spam",
        "de": "Anti-Spam",
        "th": "ป้องกันสแปม",
    },
    "blacklist_lbl": {
        "en": "Blacklist",
        "ar": "القائمة السوداء",
        "es": "Lista negra",
        "fr": "Liste noire",
        "hi": "ब्लैकलिस्ट",
        "pt": "Lista negra",
        "ru": "Чёрный список",
        "tr": "Kara Liste",
        "id": "Daftar Hitam",
        "de": "Schwarze Liste",
        "th": "บัญชีดำ",
    },
    "locks_lbl": {
        "en": "Locks",
        "ar": "القيود",
        "es": "Bloqueos",
        "fr": "Verrous",
        "hi": "लॉक",
        "pt": "Bloqueios",
        "ru": "Запреты",
        "tr": "Kilitler",
        "id": "Kunci",
        "de": "Sperren",
        "th": "การล็อก",
    },
    # ============================================
    # SECTION HEADERS
    # ============================================
    "section_general": {
        "en": "General",
        "ar": "عام",
        "es": "General",
        "fr": "Général",
        "hi": "सामान्य",
        "pt": "Geral",
        "ru": "Общее",
        "tr": "Genel",
        "id": "Umum",
        "de": "Allgemein",
        "th": "ทั่วไป",
    },
    "section_warnings": {
        "en": "Warnings",
        "ar": "التحذيرات",
        "es": "Advertencias",
        "fr": "Avertissements",
        "hi": "चेतावनियाँ",
        "pt": "Avisos",
        "ru": "Предупреждения",
        "tr": "Uyarılar",
        "id": "Peringatan",
        "de": "Warnungen",
        "th": "คำเตือน",
    },
    "section_captcha": {
        "en": "Captcha",
        "ar": "الكابتشا",
        "es": "Captcha",
        "fr": "Captcha",
        "hi": "कैप्चा",
        "pt": "Captcha",
        "ru": "Капча",
        "tr": "Captcha",
        "id": "Captcha",
        "de": "Captcha",
        "th": "แคปช่า",
    },
    "section_antiraid": {
        "en": "Anti-Raid",
        "ar": "مضاد الغارات",
        "es": "Anti-Raid",
        "fr": "Anti-Raid",
        "hi": "एंटी-रेड",
        "pt": "Anti-Raid",
        "ru": "Анти-рейд",
        "tr": "Anti-Raid",
        "id": "Anti-Raid",
        "de": "Anti-Raid",
        "th": "ป้องกันการโจมตี",
    },
    # ============================================
    # TIME LABELS
    # ============================================
    "minutes": {
        "en": "minutes",
        "ar": "دقائق",
        "es": "minutos",
        "fr": "minutes",
        "hi": "मिनट",
        "pt": "minutos",
        "ru": "минут",
        "tr": "dakika",
        "id": "menit",
        "de": "Minuten",
        "th": "นาที",
    },
    "seconds": {
        "en": "seconds",
        "ar": "ثواني",
        "es": "segundos",
        "fr": "secondes",
        "hi": "सेकंड",
        "pt": "segundos",
        "ru": "секунд",
        "tr": "saniye",
        "id": "detik",
        "de": "Sekunden",
        "th": "วินาที",
    },
    "hours": {
        "en": "hours",
        "ar": "ساعات",
        "es": "horas",
        "fr": "heures",
        "hi": "घंटे",
        "pt": "horas",
        "ru": "часов",
        "tr": "saat",
        "id": "jam",
        "de": "Stunden",
        "th": "ชั่วโมง",
    },
    "days": {
        "en": "days",
        "ar": "أيام",
        "es": "días",
        "fr": "jours",
        "hi": "दिन",
        "pt": "dias",
        "ru": "дней",
        "tr": "gün",
        "id": "hari",
        "de": "Tage",
        "th": "วัน",
    },
    "threshold_lbl": {
        "en": "Threshold",
        "ar": "الحد",
        "es": "Umbral",
        "fr": "Seuil",
        "hi": "सीमा",
        "pt": "Limite",
        "ru": "Порог",
        "tr": "Eşik",
        "id": "Ambang",
        "de": "Schwelle",
        "th": "เกณฑ์",
    },
    "timeout_lbl": {
        "en": "Timeout",
        "ar": "المهلة",
        "es": "Tiempo límite",
        "fr": "Délai",
        "hi": "समय सीमा",
        "pt": "Tempo limite",
        "ru": "Таймаут",
        "tr": "Zaman Aşımı",
        "id": "Waktu Habis",
        "de": "Zeitüberschreitung",
        "th": "หมดเวลา",
    },
    # ============================================
    # PAGE-SPECIFIC LABELS
    # ============================================
    "vote_threshold": {
        "en": "Vote Threshold",
        "ar": "حد التصويت",
        "es": "Umbral de Votación",
        "fr": "Seuil de Vote",
        "hi": "मतदान सीमा",
        "pt": "Limite de Votação",
        "ru": "Порог голосования",
        "tr": "Oylama Eşiği",
        "id": "Ambang Suara",
        "de": "Abstimmungsschwelle",
        "th": "เกณฑ์โหวต",
    },
    "vote_action": {
        "en": "Vote Action",
        "ar": "إجراء التصويت",
        "es": "Acción de Votación",
        "fr": "Action de Vote",
        "hi": "मतदान कार्रवाई",
        "pt": "Ação de Votação",
        "ru": "Действие голосования",
        "tr": "Oylama Eylemi",
        "id": "Aksi Suara",
        "de": "Abstimmungsaktion",
        "th": "การกระทำโหวต",
    },
    "auto_detect_scams": {
        "en": "Auto-Detect Scams",
        "ar": "الكشف التلقائي عن الاحتيال",
        "es": "Detectar Estafas Automáticamente",
        "fr": "Détection Automatique des Arnaques",
        "hi": "घोटालों की स्वचालित पहचान",
        "pt": "Detectar Golpes Automaticamente",
        "ru": "Автоопределение мошенничества",
        "tr": "Dolandırıcılığı Otomatik Algıla",
        "id": "Deteksi Penipuan Otomatis",
        "de": "Betrug automatisch erkennen",
        "th": "ตรวจจับการหลอกลวงอัตโนมัติ",
    },
    "night_schedule": {
        "en": "Night Schedule",
        "ar": "جدول الليل",
        "es": "Horario Nocturno",
        "fr": "Horario Nocturne",
        "hi": "नाइट शेड्यूल",
        "pt": "Horário Noturno",
        "ru": "Расписание ночного режима",
        "tr": "Gece Programı",
        "id": "Jadwal Malam",
        "de": "Nachtzeitplan",
        "th": "กำหนดการกลางคืน",
    },
    "night_start_lbl": {
        "en": "Start Time",
        "ar": "وقت البدء",
        "es": "Hora de Inicio",
        "fr": "Heure de Début",
        "hi": "प्रारंभ समय",
        "pt": "Hora de Início",
        "ru": "Время начала",
        "tr": "Başlangıç Saati",
        "id": "Waktu Mulai",
        "de": "Startzeit",
        "th": "เวลาเริ่มต้น",
    },
    "night_end_lbl": {
        "en": "End Time",
        "ar": "وقت الانتهاء",
        "es": "Hora de Fin",
        "fr": "Heure de Fin",
        "hi": "समाप्ति समय",
        "pt": "Hora de Término",
        "ru": "Время окончания",
        "tr": "Bitiş Saati",
        "id": "Waktu Selesai",
        "de": "Endzeit",
        "th": "เวลาสิ้นสุด",
    },
    "timezone_lbl": {
        "en": "Timezone",
        "ar": "المنطقة الزمنية",
        "es": "Zona Horaria",
        "fr": "Fuseau Horaire",
        "hi": "समय क्षेत्र",
        "pt": "Fuso Horário",
        "ru": "Часовой пояс",
        "tr": "Saat Dilimi",
        "id": "Zona Waktu",
        "de": "Zeitzone",
        "th": "เขตเวลา",
    },
    "night_message_lbl": {
        "en": "Night Message",
        "ar": "رسالة الليل",
        "es": "Mensaje Nocturno",
        "fr": "Message Nocturne",
        "hi": "नाइट संदेश",
        "pt": "Mensagem Noturna",
        "ru": "Ночное сообщение",
        "tr": "Gece Mesajı",
        "id": "Pesan Malam",
        "de": "Nachtnachricht",
        "th": "ข้อความกลางคืน",
    },
    "morning_msg_lbl": {
        "en": "Morning Message",
        "ar": "رسالة الصباح",
        "es": "Mensaje Matutino",
        "fr": "Message Matinal",
        "hi": "सुबह का संदेश",
        "pt": "Mensagem Matinal",
        "ru": "Утреннее сообщение",
        "tr": "Sabah Mesajı",
        "id": "Pesan Pagi",
        "de": "Frühnachricht",
        "th": "ข้อความตอนเช้า",
    },
    "fed_name_lbl": {
        "en": "Federation Name",
        "ar": "اسم الاتحاد",
        "es": "Nombre de Federación",
        "fr": "Nom de la Fédération",
        "hi": "संघ का नाम",
        "pt": "Nome da Federação",
        "ru": "Название федерации",
        "tr": "Federasyon Adı",
        "id": "Nama Federasi",
        "de": "Föderationsname",
        "th": "ชื่อสหพันธ์",
    },
    "invite_code_lbl": {
        "en": "Invite Code",
        "ar": "كود الدعوة",
        "es": "Código de Invitación",
        "fr": "Code d'Invitation",
        "hi": "आमंत्रण कोड",
        "pt": "Código de Convite",
        "ru": "Код приглашения",
        "tr": "Davet Kodu",
        "id": "Kode Undangan",
        "de": "Einladungscode",
        "th": "รหัสเชิญ",
    },
    "ban_propagation": {
        "en": "Ban Propagation",
        "ar": "انتشار الحظر",
        "es": "Propagación de Ban",
        "fr": "Propagation du Ban",
        "hi": "बैन प्रसार",
        "pt": "Propagação de Ban",
        "ru": "Распространение бана",
        "tr": "Yasak Yayılımı",
        "id": "Penegakan Blokir",
        "de": "Ban-Ausbreitung",
        "th": "การขยายแบน",
    },
    "share_reputation": {
        "en": "Share Reputation",
        "ar": "مشاركة السمعة",
        "es": "Compartir Reputación",
        "fr": "Partager la Réputation",
        "hi": "प्रतिष्ठा साझा करें",
        "pt": "Compartilhar Reputação",
        "ru": "Делиться репутацией",
        "tr": "İtibar Paylaş",
        "id": "Bagikan Reputasi",
        "de": "Reputation teilen",
        "th": "แชร์ชื่อเสียง",
    },
    "my_lang_lbl": {
        "en": "My Language",
        "ar": "لغتي",
        "es": "Mi Idioma",
        "fr": "Ma Langue",
        "hi": "मेरी भाषा",
        "pt": "Meu Idioma",
        "ru": "Мой язык",
        "tr": "Dilim",
        "id": "Bahasa Saya",
        "de": "Meine Sprache",
        "th": "ภาษาของฉัน",
    },
    "group_lang_lbl": {
        "en": "Group Language",
        "ar": "لغة المجموعة",
        "es": "Idioma del Grupo",
        "fr": "Langue du Groupe",
        "hi": "समूह की भाषा",
        "pt": "Idioma do Grupo",
        "ru": "Язык группы",
        "tr": "Grup Dili",
        "id": "Bahasa Grup",
        "de": "Gruppensprache",
        "th": "ภาษากลุ่ม",
    },
    "auto_detected": {
        "en": "Auto-detected",
        "ar": "اكتشاف تلقائي",
        "es": "Auto-detectado",
        "fr": "Auto-détecté",
        "hi": "स्वतः पहचाना गया",
        "pt": "Auto-detectado",
        "ru": "Автоопределено",
        "tr": "Otomatik Algılandı",
        "id": "Tereteksi Otomatis",
        "de": "Automatisch erkannt",
        "th": "ตรวจพบอัตโนมัติ",
    },
    "manual_override": {
        "en": "Manual Override",
        "ar": "تجاوز يدوي",
        "es": "Anulación Manual",
        "fr": "Override Manuel",
        "hi": "मैन्युअल ओवरराइड",
        "pt": "Substituição Manual",
        "ru": "Ручная настройка",
        "tr": "Manuel Geçersiz Kılma",
        "id": "Penggantian Manual",
        "de": "Manuelle Überschreibung",
        "th": "แทนที่ด้วยตนเอง",
    },
    # ============================================
    # TOAST MESSAGES
    # ============================================
    "toast_save_success": {
        "en": "Saved successfully!",
        "ar": "تم الحفظ بنجاح!",
        "es": "¡Guardado exitosamente!",
        "fr": "Enregistré avec succès!",
        "hi": "सफलतापूर्वक सहेजा गया!",
        "pt": "Salvo com sucesso!",
        "ru": "Успешно сохранено!",
        "tr": "Başarıyla kaydedildi!",
        "id": "Berhasil disimpan!",
        "de": "Erfolgreich gespeichert!",
        "th": "บันทึกสำเร็จ!",
    },
    "toast_delete_success": {
        "en": "Deleted successfully!",
        "ar": "تم الحذف بنجاح!",
        "es": "¡Eliminado exitosamente!",
        "fr": "Supprimé avec succès!",
        "hi": "सफलतापूर्वक हटाया गया!",
        "pt": "Excluído com sucesso!",
        "ru": "Успешно удалено!",
        "tr": "Başarıyla silindi!",
        "id": "Berhasil dihapus!",
        "de": "Erfolgreich gelöscht!",
        "th": "ลบสำเร็จ!",
    },
    "toast_copy": {
        "en": "Copied to clipboard!",
        "ar": "تم النسخ إلى الحافظة!",
        "es": "¡Copiado al portapapeles!",
        "fr": "Copié dans le presse-papiers!",
        "hi": "क्लिपबोर्ड पर कॉपी किया गया!",
        "pt": "Copiado para a área de transferência!",
        "ru": "Скопировано в буфер обмена!",
        "tr": "Panoya kopyalandı!",
        "id": "Disalin ke clipboard!",
        "de": "In Zwischenablage kopiert!",
        "th": "คัดลอกไปยังคลิปบอร์ด!",
    },
    "toast_no_group": {
        "en": "No group selected",
        "ar": "لم يتم تحديد مجموعة",
        "es": "Ningún grupo seleccionado",
        "fr": "Aucun groupe sélectionné",
        "hi": "कोई समूह नहीं चुना गया",
        "pt": "Nenhum grupo selecionado",
        "ru": "Группа не выбрана",
        "tr": "Grup seçilmedi",
        "id": "Tidak ada grup dipilih",
        "de": "Keine Gruppe ausgewählt",
        "th": "ยังไม่ได้เลือกกลุ่ม",
    },
    "loading": {
        "en": "Loading...",
        "ar": "جارٍ التحميل...",
        "es": "Cargando...",
        "fr": "Chargement...",
        "hi": "लोड हो रहा है...",
        "pt": "Carregando...",
        "ru": "Загрузка...",
        "tr": "Yükleniyor...",
        "id": "Memuat...",
        "de": "Laden...",
        "th": "กำลังโหลด...",
    },
    "saved": {
        "en": "Saved!",
        "ar": "تم الحفظ!",
        "es": "¡Guardado!",
        "fr": "Enregistré!",
        "hi": "सहेजा गया!",
        "pt": "Salvo!",
        "ru": "Сохранено!",
        "tr": "Kaydedildi!",
        "id": "Tersimpan!",
        "de": "Gespeichert!",
        "th": "บันทึกแล้ว!",
    },
    "error": {
        "en": "Error",
        "ar": "خطأ",
        "es": "Error",
        "fr": "Erreur",
        "hi": "त्रुटि",
        "pt": "Erro",
        "ru": "Ошибка",
        "tr": "Hata",
        "id": "Kesalahan",
        "de": "Fehler",
        "th": "ข้อผิดพลาด",
    },
    "select_group": {
        "en": "Select a group",
        "ar": "اختر مجموعة",
        "es": "Seleccionar un grupo",
        "fr": "Sélectionner un groupe",
        "hi": "एक समूह चुनें",
        "pt": "Selecionar um grupo",
        "ru": "Выберите группу",
        "tr": "Bir grup seçin",
        "id": "Pilih grup",
        "de": "Gruppe auswählen",
        "th": "เลือกกลุ่ม",
    },
    # ============================================
    # LANGUAGE PAGE SPECIFIC
    # ============================================
    "lang_notice_title": {
        "en": "This changes the mini app interface language for you only.",
        "ar": "هذا يغير لغة واجهة التطبيق المصغرة لك فقط.",
        "es": "Esto cambia el idioma de la interfaz de la mini app solo para ti.",
        "fr": "Cela change la langue de l'interface de la mini app uniquement pour vous.",
        "hi": "यह केवल आपके लिए मिनी ऐप इंटरफेस की भाषा बदलता है।",
        "pt": "Isso muda o idioma da interface do mini app apenas para você.",
        "ru": "Это изменяет язык интерфейса мини-приложения только для вас.",
        "tr": "Bu, yalnızca sizin için mini uygulama arayüz dilini değiştirir.",
        "id": "Ini mengubah bahasa antarmuka mini app hanya untuk Anda.",
        "de": "Dies ändert die Sprache der Mini-App-Oberfläche nur für Sie.",
        "th": "การตั้งค่านี้จะเปลี่ยนภาษาของหน้าจอแอปสำหรับคุณเท่านั้น",
    },
    "lang_notice_body": {
        "en": "To change the language the bot uses when sending messages to your group, go to",
        "ar": "لتغيير اللغة التي يستخدمها البوت عند إرسال الرسائل إلى مجموعتك، انتقل إلى",
        "es": "Para cambiar el idioma que el bot usa al enviar mensajes a tu grupo, ve a",
        "fr": "Pour changer la langue utilisée par le bot lors de l'envoi de messages à votre groupe, allez à",
        "hi": "बॉट द्वारा आपके समूह में संदेश भेजते समय उपयोग की जाने वाली भाषा बदलने के लिए, यहाँ जाएं",
        "pt": "Para alterar o idioma que o bot usa ao enviar mensagens para seu grupo, vá para",
        "ru": "Чтобы изменить язык, который бот использует при отправке сообщений в вашу группу, перейдите в",
        "tr": "Botun grubunuza mesaj gönderirken kullandığı dili değiştirmek için şuraya gidin",
        "id": "Untuk mengubah bahasa yang digunakan bot saat mengirim pesan ke grup Anda, buka",
        "de": "Um die Sprache zu ändern, die der Bot beim Senden von Nachrichten an Ihre Gruppe verwendet, gehen Sie zu",
        "th": "หากต้องการเปลี่ยนภาษาที่บอทใช้ส่งข้อความไปยังกลุ่มของคุณ ไปที่",
    },
    "lang_notice_link": {
        "en": "Settings → Group Identity → Bot Message Language",
        "ar": "الإعدادات → هوية المجموعة → لغة رسائل البوت",
        "es": "Configuración → Identidad del Grupo → Idioma de Mensajes del Bot",
        "fr": "Paramètres → Identité du Groupe → Langue des Messages du Bot",
        "hi": "सेटिंग्स → समूह पहचान → बॉट संदेश भाषा",
        "pt": "Configurações → Identidade do Grupo → Idioma das Mensagens do Bot",
        "ru": "Настройки → Идентичность Группы → Язык Сообщений Бота",
        "tr": "Ayarlar → Grup Kimliği → Bot Mesaj Dili",
        "id": "Pengaturan → Identitas Grup → Bahasa Pesan Bot",
        "de": "Einstellungen → Gruppenidentität → Bot-Nachrichtensprache",
        "th": "การตั้งค่า → ข้อมูลกลุ่ม → ภาษาข้อความบอท",
    },
    "lang_subtitle": {
        "en": "Choose your preferred interface language",
        "ar": "اختر لغة الواجهة المفضلة لديك",
        "es": "Elige tu idioma de interfaz preferido",
        "fr": "Choisissez votre langue d'interface préférée",
        "hi": "अपनी पसंदीदा इंटरफेस भाषा चुनें",
        "pt": "Escolha seu idioma de interface preferido",
        "ru": "Выберите предпочитаемый язык интерфейса",
        "tr": "Tercih ettiğiniz arayüz dilini seçin",
        "id": "Pilih bahasa antarmuka yang Anda sukai",
        "de": "Wählen Sie Ihre bevorzugte Oberflächensprache",
        "th": "เลือกภาษาหน้าจอที่คุณต้องการ",
    },
    "lang_changed": {
        "en": "Language changed successfully!",
        "ar": "تم تغيير اللغة بنجاح!",
        "es": "¡Idioma cambiado exitosamente!",
        "fr": "Langue changée avec succès!",
        "hi": "भाषा सफलतापूर्वक बदली गई!",
        "pt": "Idioma alterado com sucesso!",
        "ru": "Язык успешно изменён!",
        "tr": "Dil başarıyla değiştirildi!",
        "id": "Bahasa berhasil diubah!",
        "de": "Sprache erfolgreich geändert!",
        "th": "เปลี่ยนภาษาสำเร็จ!",
    },
    "current": {
        "en": "Current",
        "ar": "الحالي",
        "es": "Actual",
        "fr": "Actuel",
        "hi": "वर्तमान",
        "pt": "Atual",
        "ru": "Текущий",
        "tr": "Mevcut",
        "id": "Saat ini",
        "de": "Aktuell",
        "th": "ปัจจุบัน",
    },
    "lang_detected_title": {
        "en": "Language Detected",
        "ar": "تم اكتشاف اللغة",
        "es": "Idioma Detectado",
        "fr": "Langue Détectée",
        "hi": "भाषा का पता लगा",
        "pt": "Idioma Detectado",
        "ru": "Язык Обнаружен",
        "tr": "Dil Algılandı",
        "id": "Bahasa Terdeteksi",
        "de": "Sprache Erkannt",
        "th": "ตรวจพบภาษา",
    },
    "lang_detected_body": {
        "en": "We detected you may be using {lang}. Would you like to use this language?",
        "ar": "لقد اكتشفنا أنك قد تستخدم {lang}. هل ترغب في استخدام هذه اللغة؟",
        "es": "Detectamos que podrías estar usando {lang}. ¿Te gustaría usar este idioma?",
        "fr": "Nous avons détecté que vous utilisez peut-être {lang}. Voulez-vous utiliser cette langue?",
        "hi": "हमने पाया कि आप {lang} का उपयोग कर रहे हो सकते हैं। क्या आप इस भाषा का उपयोग करना चाहेंगे?",
        "pt": "Detectamos que você pode estar usando {lang}. Gostaria de usar este idioma?",
        "ru": "Мы обнаружили, что вы, возможно, используете {lang}. Хотите использовать этот язык?",
        "tr": "{lang} kullanıyor olabileceğinizi tespit ettik. Bu dili kullanmak ister misiniz?",
        "id": "Kami mendeteksi Anda mungkin menggunakan {lang}. Apakah Anda ingin menggunakan bahasa ini?",
        "de": "Wir haben festgestellt, dass Sie möglicherweise {lang} verwenden. Möchten Sie diese Sprache verwenden?",
        "th": "เราตรวจพบว่าคุณอาจกำลังใช้ {lang} คุณต้องการใช้ภาษานี้หรือไม่?",
    },
    "lang_use_detected": {
        "en": "Yes, use this language",
        "ar": "نعم، استخدم هذه اللغة",
        "es": "Sí, usar este idioma",
        "fr": "Oui, utiliser cette langue",
        "hi": "हां, इस भाषा का उपयोग करें",
        "pt": "Sim, usar este idioma",
        "ru": "Да, использовать этот язык",
        "tr": "Evet, bu dili kullan",
        "id": "Ya, gunakan bahasa ini",
        "de": "Ja, diese Sprache verwenden",
        "th": "ใช่ ใช้ภาษานี้",
    },
    "lang_keep_english": {
        "en": "No, keep English",
        "ar": "لا، احتفظ بالإنجليزية",
        "es": "No, mantener inglés",
        "fr": "Non, garder l'anglais",
        "hi": "नहीं, अंग्रेजी रखें",
        "pt": "Não, manter inglês",
        "ru": "Нет, оставить английский",
        "tr": "Hayır, İngilizce'yi koru",
        "id": "Tidak, tetap gunakan bahasa Inggris",
        "de": "Nein, Englisch beibehalten",
        "th": "ไม่ ใช้ภาษาอังกฤษต่อ",
    },
    "lang_auto_detect_hint": {
        "en": "Language is automatically detected from your name, bio, and messages.",
        "ar": "يتم اكتشاف اللغة تلقائيًا من اسمك ونبذة عنك ورسائلك.",
        "es": "El idioma se detecta automáticamente de tu nombre, biografía y mensajes.",
        "fr": "La langue est détectée automatiquement à partir de votre nom, bio et messages.",
        "hi": "भाषा आपके नाम, बायो और संदेशों से स्वचालित रूप से पता लगाई जाती है।",
        "pt": "O idioma é detectado automaticamente a partir do seu nome, bio e mensagens.",
        "ru": "Язык определяется автоматически по вашему имени, биографии и сообщениям.",
        "tr": "Dil, adınızdan, biyografinizden ve mesajlarınızdan otomatik olarak algılanır.",
        "id": "Bahasa terdeteksi secara otomatis dari nama, bio, dan pesan Anda.",
        "de": "Die Sprache wird automatisch aus Ihrem Namen, Ihrer Bio und Ihren Nachrichten erkannt.",
        "th": "ภาษาจะถูกตรวจจับอัตโนมัติจากชื่อ ประวัติ และข้อความของคุณ",
    },
    # ============================================
    # MODERATION ERRORS (Issue 8A/8D)
    # ============================================
    "no_target": {
        "en": "❌ Reply to a message or provide a username/ID.",
        "es": "❌ Responde a un mensaje o proporciona un nombre de usuario/ID.",
        "fr": "❌ Répondez à un message ou fournissez un nom d'utilisateur/ID.",
        "de": "❌ Antworte auf eine Nachricht oder gib einen Benutzernamen/ID an.",
        "ru": "❌ Ответьте на сообщение или укажите имя пользователя/ID.",
        "pt": "❌ Responda a uma mensagem ou forneça um nome de usuário/ID.",
        "ar": "❌ رد على رسالة أو قدم اسم مستخدم/ID.",
        "hi": "❌ किसी संदेश का उत्तर दें या उपयोगकर्ता नाम/ID प्रदान करें।",
        "tr": "❌ Bir mesaja yanıt verin veya bir kullanıcı adı/ID sağlayın.",
        "id": "❌ Balas pesan atau berikan nama pengguna/ID.",
        "th": "❌ ตอบกลับข้อความหรือระบุชื่อผู้ใช้/ID",
    },
    "cant_act_admin": {
        "en": "❌ I cannot act on an admin.",
        "es": "❌ No puedo actuar sobre un administrador.",
        "fr": "❌ Je ne peux pas agir sur un administrateur.",
        "de": "❌ Ich kann nicht gegen einen Administrator vorgehen.",
        "ru": "❌ Я не могу действовать против администратора.",
        "pt": "❌ Não posso agir sobre um administrador.",
        "ar": "❌ لا يمكنني التصرف مع مسؤول.",
        "hi": "❌ मैं किसी व्यवस्थापक पर कार्रवाई नहीं कर सकता।",
        "tr": "❌ Bir yöneticiye karşı işlem yapamam.",
        "id": "❌ Saya tidak bisa bertindak terhadap admin.",
        "th": "❌ ฉันไม่สามารถดำเนินการกับผู้ดูแลระบบได้",
    },
    "cant_act_owner": {
        "en": "❌ I cannot act on the group owner.",
        "es": "❌ No puedo actuar sobre el propietario del grupo.",
        "fr": "❌ Je ne peux pas agir sur le propriétaire du groupe.",
        "de": "❌ Ich kann nicht gegen den Gruppenbesitzer vorgehen.",
        "ru": "❌ Я не могу действовать против владельца группы.",
        "pt": "❌ Não posso agir sobre o proprietário do grupo.",
        "ar": "❌ لا يمكنني التصرف مع مالك المجموعة.",
        "hi": "❌ मैं समूह स्वामी पर कार्रवाई नहीं कर सकता।",
        "tr": "❌ Grup sahibine karşı işlem yapamam.",
        "id": "❌ Saya tidak bisa bertindak terhadap pemilik grup.",
        "th": "❌ ฉันไม่สามารถดำเนินการกับเจ้าของกลุ่มได้",
    },
    "cant_act_self": {
        "en": "❌ You cannot act on yourself.",
        "es": "❌ No puedes actuar sobre ti mismo.",
        "fr": "❌ Vous ne pouvez pas agir sur vous-même.",
        "de": "❌ Du kannst nicht gegen dich selbst vorgehen.",
        "ru": "❌ Вы не можете действовать против себя.",
        "pt": "❌ Você não pode agir sobre si mesmo.",
        "ar": "❌ لا يمكنك التصرف مع نفسك.",
        "hi": "❌ आप खुद पर कार्रवाई नहीं कर सकते।",
        "tr": "❌ Kendine karşı işlem yapamazsın.",
        "id": "❌ Anda tidak bisa bertindak terhadap diri sendiri.",
        "th": "❌ คุณไม่สามารถดำเนินการกับตัวเองได้",
    },
    "cant_act_bot": {
        "en": "❌ I cannot act on myself.",
        "es": "❌ No puedo actuar sobre mí mismo.",
        "fr": "❌ Je ne peux pas agir sur moi-même.",
        "de": "❌ Ich kann nicht gegen mich selbst vorgehen.",
        "ru": "❌ Я не могу действовать против себя.",
        "pt": "❌ Não posso agir sobre mim mesmo.",
        "ar": "❌ لا يمكنني التصرف مع نفسي.",
        "hi": "❌ मैं खुद पर कार्रवाई नहीं कर सकता।",
        "tr": "❌ Kendime karşı işlem yapamam.",
        "id": "❌ Saya tidak bisa bertindak terhadap diri sendiri.",
        "th": "❌ ฉันไม่สามารถดำเนินการกับตัวเองได้",
    },
    "no_permission": {
        "en": "❌ You don't have permission to do this.",
        "es": "❌ No tienes permiso para hacer esto.",
        "fr": "❌ Vous n'avez pas la permission de faire cela.",
        "de": "❌ Du hast keine Berechtigung, dies zu tun.",
        "ru": "❌ У вас нет разрешения на это.",
        "pt": "❌ Você não tem permissão para fazer isso.",
        "ar": "❌ ليس لديك إذن للقيام بذلك.",
        "hi": "❌ आपके पास ऐसा करने की अनुमति नहीं है।",
        "tr": "❌ Bunu yapmak için izniniz yok.",
        "id": "❌ Anda tidak memiliki izin untuk melakukan ini.",
        "th": "❌ คุณไม่มีสิทธิ์ทำเช่นนี้",
    },
    "user_not_found": {
        "en": "❌ User not found in this group.",
        "es": "❌ Usuario no encontrado en este grupo.",
        "fr": "❌ Utilisateur non trouvé dans ce groupe.",
        "de": "❌ Benutzer in dieser Gruppe nicht gefunden.",
        "ru": "❌ Пользователь не найден в этой группе.",
        "pt": "❌ Usuário não encontrado neste grupo.",
        "ar": "❌ لم يتم العثور على المستخدم في هذه المجموعة.",
        "hi": "❌ इस समूह में उपयोगकर्ता नहीं मिला।",
        "tr": "❌ Kullanıcı bu grupta bulunamadı.",
        "id": "❌ Pengguna tidak ditemukan di grup ini.",
        "th": "❌ ไม่พบผู้ใช้ในกลุ่มนี้",
    },
    "already_banned": {
        "en": "❌ This user is already banned.",
        "es": "❌ Este usuario ya está baneado.",
        "fr": "❌ Cet utilisateur est déjà banni.",
        "de": "❌ Dieser Benutzer ist bereits gebannt.",
        "ru": "❌ Этот пользователь уже заблокирован.",
        "pt": "❌ Este usuário já está banido.",
        "ar": "❌ هذا المستخدم محظور بالفعل.",
        "hi": "❌ यह उपयोगकर्ता पहले से ही प्रतिबंधित है।",
        "tr": "❌ Bu kullanıcı zaten yasaklanmış.",
        "id": "❌ Pengguna ini sudah diblokir.",
        "th": "❌ ผู้ใช้รายนี้ถูกแบนอยู่แล้ว",
    },
    "not_banned": {
        "en": "❌ This user is not banned.",
        "es": "❌ Este usuario no está baneado.",
        "fr": "❌ Cet utilisateur n'est pas banni.",
        "de": "❌ Dieser Benutzer ist nicht gebannt.",
        "ru": "❌ Этот пользователь не заблокирован.",
        "pt": "❌ Este usuário não está banido.",
        "ar": "❌ هذا المستخدم ليس محظوراً.",
        "hi": "❌ यह उपयोगकर्ता प्रतिबंधित नहीं है।",
        "tr": "❌ Bu kullanıcı yasaklı değil.",
        "id": "❌ Pengguna ini tidak diblokir.",
        "th": "❌ ผู้ใช้รายนี้ไม่ถูกแบน",
    },
    "already_muted": {
        "en": "❌ This user is already muted.",
        "es": "❌ Este usuario ya está silenciado.",
        "fr": "❌ Cet utilisateur est déjà muet.",
        "de": "❌ Dieser Benutzer ist bereits stummgeschaltet.",
        "ru": "❌ Этот пользователь уже заглушён.",
        "pt": "❌ Este usuário já está mutado.",
        "ar": "❌ هذا المستخدم مكتوم بالفعل.",
        "hi": "❌ यह उपयोगकर्ता पहले से ही म्यूट है।",
        "tr": "❌ Bu kullanıcı zaten susturulmuş.",
        "id": "❌ Pengguna ini sudah dibisukan.",
        "th": "❌ ผู้ใช้รายนี้ถูกปิดเสียงอยู่แล้ว",
    },
    "not_muted": {
        "en": "❌ This user is not muted.",
        "es": "❌ Este usuario no está silenciado.",
        "fr": "❌ Cet utilisateur n'est pas muet.",
        "de": "❌ Dieser Benutzer ist nicht stummgeschaltet.",
        "ru": "❌ Этот пользователь не заглушён.",
        "pt": "❌ Este usuário não está mutado.",
        "ar": "❌ هذا المستخدم ليس مكتوماً.",
        "hi": "❌ यह उपयोगकर्ता म्यूट नहीं है।",
        "tr": "❌ Bu kullanıcı susturulmamış.",
        "id": "❌ Pengguna ini tidak dibisukan.",
        "th": "❌ ผู้ใช้รายนี้ไม่ถูกปิดเสียง",
    },
    "invalid_time": {
        "en": "❌ Invalid time format. Use: 30m, 1h, 7d, 1w",
        "es": "❌ Formato de tiempo inválido. Usa: 30m, 1h, 7d, 1w",
        "fr": "❌ Format de temps invalide. Utilisez: 30m, 1h, 7d, 1w",
        "de": "❌ Ungültiges Zeitformat. Verwende: 30m, 1h, 7d, 1w",
        "ru": "❌ Неверный формат времени. Используйте: 30m, 1h, 7d, 1w",
        "pt": "❌ Formato de tempo inválido. Use: 30m, 1h, 7d, 1w",
        "ar": "❌ تنسيق وقت غير صالح. استخدم: 30m, 1h, 7d, 1w",
        "hi": "❌ अमान्य समय प्रारूप। उपयोग करें: 30m, 1h, 7d, 1w",
        "tr": "❌ Geçersiz zaman formatı. Şunu kullanın: 30m, 1h, 7d, 1w",
        "id": "❌ Format waktu tidak valid. Gunakan: 30m, 1h, 7d, 1w",
        "th": "❌ รูปแบบเวลาไม่ถูกต้อง ใช้: 30m, 1h, 7d, 1w",
    },
    "bot_no_rights": {
        "en": "❌ I don't have enough rights. Make me an admin first.",
        "es": "❌ No tengo suficientes derechos. Hazme administrador primero.",
        "fr": "❌ Je n'ai pas assez de droits. Faites de moi un administrateur d'abord.",
        "de": "❌ Ich habe nicht genügend Rechte. Mach mich zuerst zum Administrator.",
        "ru": "❌ У меня недостаточно прав. Сначала сделайте меня администратором.",
        "pt": "❌ Não tenho direitos suficientes. Torne-me um administrador primeiro.",
        "ar": "❌ ليس لدي حقوق كافية. اجعلني مسؤولاً أولاً.",
        "hi": "❌ मेरे पास पर्याप्त अधिकार नहीं हैं। मुझे पहले एडमिन बनाएं।",
        "tr": "❌ Yeterli yetkim yok. Önce beni yönetici yapın.",
        "id": "❌ Saya tidak memiliki cukup hak. Jadikan saya admin terlebih dahulu.",
        "th": "❌ ฉันไม่มีสิทธิ์เพียงพอ ตั้งค่าให้ฉันเป็นผู้ดูแลระบบก่อน",
    },
    "muted_max_warns": {
        "en": "🔇 {name} reached max warnings and was muted.",
        "es": "🔇 {name} alcanzó el máximo de advertencias y fue silenciado.",
        "fr": "🔇 {name} a atteint le maximum d'avertissements et a été muté.",
        "de": "🔇 {name} hat die maximale Anzahl an Warnungen erreicht und wurde stummgeschaltet.",
        "ru": "🔇 {name} достиг максимума предупреждений и был заглушён.",
        "pt": "🔇 {name} atingiu o máximo de avisos e foi mutado.",
        "ar": "🔇 وصل {name} إلى الحد الأقصى من التحذيرات وتم كتمه.",
        "hi": "🔇 {name} अधिकतम चेतावनी तक पहुँच गया और म्यूट कर दिया गया।",
        "tr": "🔇 {name} maksimum uyarı sayısına ulaştı ve susturuldu.",
        "id": "🔇 {name} mencapai peringatan maksimum dan dibisukan.",
        "th": "🔇 {name} ถึงขีดจำกัดคำเตือนและถูกปิดเสียง",
    },
    "banned_max_warns": {
        "en": "🚫 {name} reached max warnings and was banned.",
        "es": "🚫 {name} alcanzó el máximo de advertencias y fue baneado.",
        "fr": "🚫 {name} a atteint le maximum d'avertissements et a été banni.",
        "de": "🚫 {name} hat die maximale Anzahl an Warnungen erreicht und wurde gebannt.",
        "ru": "🚫 {name} достиг максимума предупреждений и был заблокирован.",
        "pt": "🚫 {name} atingiu o máximo de avisos e foi banido.",
        "ar": "🚫 وصل {name} إلى الحد الأقصى من التحذيرات وتم حظره.",
        "hi": "🚫 {name} अधिकतम चेतावनी तक पहुँच गया और प्रतिबंधित कर दिया गया।",
        "tr": "🚫 {name} maksimum uyarı sayısına ulaştı ve yasaklandı.",
        "id": "🚫 {name} mencapai peringatan maksimum dan diblokir.",
        "th": "🚫 {name} ถึงขีดจำกัดคำเตือนและถูกแบน",
    },
    "kicked_max_warns": {
        "en": "👢 {name} reached max warnings and was kicked.",
        "es": "👢 {name} alcanzó el máximo de advertencias y fue expulsado.",
        "fr": "👢 {name} a atteint le maximum d'avertissements et a été expulsé.",
        "de": "👢 {name} hat die maximale Anzahl an Warnungen erreicht und wurde entfernt.",
        "ru": "👢 {name} достиг максимума предупреждений и был исключён.",
        "pt": "👢 {name} atingiu o máximo de avisos e foi expulso.",
        "ar": "👢 وصل {name} إلى الحد الأقصى من التحذيرات وتم طرده.",
        "hi": "👢 {name} अधिकतम चेतावनी तक पहुँच गया और निकाल दिया गया।",
        "tr": "👢 {name} maksimum uyarı sayısına ulaştı ve atıldı.",
        "id": "👢 {name} mencapai peringatan maksimum dan ditendang.",
        "th": "👢 {name} ถึงขีดจำกัดคำเตือนและถูกเตะออก",
    },
    "ban_confirmed": {
        "en": "✅ Banned | {name} 📋 Reason: {reason}",
        "es": "✅ Baneado | {name} 📋 Razón: {reason}",
        "fr": "✅ Banni | {name} 📋 Raison: {reason}",
        "de": "✅ Gebannt | {name} 📋 Grund: {reason}",
        "ru": "✅ Заблокирован | {name} 📋 Причина: {reason}",
        "pt": "✅ Banido | {name} 📋 Motivo: {reason}",
        "ar": "✅ تم الحظر | {name} 📋 السبب: {reason}",
        "hi": "✅ प्रतिबंधित | {name} 📋 कारण: {reason}",
        "tr": "✅ Yasaklandı | {name} 📋 Sebep: {reason}",
        "id": "✅ Diblokir | {name} 📋 Alasan: {reason}",
        "th": "✅ แบนสำเร็จ | {name} 📋 เหตุผล: {reason}",
    },
    "mute_confirmed": {
        "en": "🔇 Muted | {name} for {duration} 📋 Reason: {reason}",
        "es": "🔇 Silenciado | {name} por {duration} 📋 Razón: {reason}",
        "fr": "🔇 Muté | {name} pour {duration} 📋 Raison: {reason}",
        "de": "🔇 Stummgeschaltet | {name} für {duration} 📋 Grund: {reason}",
        "ru": "🔇 Заглушён | {name} на {duration} 📋 Причина: {reason}",
        "pt": "🔇 Mutado | {name} por {duration} 📋 Motivo: {reason}",
        "ar": "🔇 تم الكتم | {name} لمدة {duration} 📋 السبب: {reason}",
        "hi": "🔇 म्यूट किया गया | {name} {duration} के लिए 📋 कारण: {reason}",
        "tr": "🔇 Susturuldu | {name}, {duration} boyunca 📋 Sebep: {reason}",
        "id": "🔇 Dibisukan | {name} selama {duration} 📋 Alasan: {reason}",
        "th": "🔇 ปิดเสียง | {name} เป็นเวลา {duration} 📋 เหตุผล: {reason}",
    },
    "kick_confirmed": {
        "en": "👢 Kicked | {name} 📋 Reason: {reason}",
        "es": "👢 Expulsado | {name} 📋 Razón: {reason}",
        "fr": "👢 Expulsé | {name} 📋 Raison: {reason}",
        "de": "👢 Entfernt | {name} 📋 Grund: {reason}",
        "ru": "👢 Исключён | {name} 📋 Причина: {reason}",
        "pt": "👢 Expulso | {name} 📋 Motivo: {reason}",
        "ar": "👢 تم الطرد | {name} 📋 السبب: {reason}",
        "hi": "👢 निकाला गया | {name} 📋 कारण: {reason}",
        "tr": "👢 Atıldı | {name} 📋 Sebep: {reason}",
        "id": "👢 Ditendang | {name} 📋 Alasan: {reason}",
        "th": "👢 เตะออก | {name} 📋 เหตุผล: {reason}",
    },
    "promote_confirmed": {
        "en": "✅ {name} promoted to admin.",
        "es": "✅ {name} promovido a administrador.",
        "fr": "✅ {name} promu administrateur.",
        "de": "✅ {name} zum Administrator befördert.",
        "ru": "✅ {name} повышен до администратора.",
        "pt": "✅ {name} promovido a administrador.",
        "ar": "✅ تم ترقية {name} إلى مسؤول.",
        "hi": "✅ {name} को एडमिन बनाया गया।",
        "tr": "✅ {name} yönetici olarak atandı.",
        "id": "✅ {name} dipromosikan menjadi admin.",
        "th": "✅ {name} ได้รับการแต่งตั้งเป็นผู้ดูแลระบบ",
    },
    "demote_confirmed": {
        "en": "✅ {name} demoted.",
        "es": "✅ {name} degradado.",
        "fr": "✅ {name} rétrogradé.",
        "de": "✅ {name} degradiert.",
        "ru": "✅ {name} понижен в должности.",
        "pt": "✅ {name} rebaixado.",
        "ar": "✅ تم تخفيض رتبة {name}.",
        "hi": "✅ {name} का पद घटाया गया।",
        "tr": "✅ {name} rütbesi düşürüldü.",
        "id": "✅ {name} diturunkan jabatannya.",
        "th": "✅ {name} ถูกลดระดับ",
    },
    "note_saved": {
        "en": "✅ Note *{name}* saved.",
        "es": "✅ Nota *{name}* guardada.",
        "fr": "✅ Note *{name}* enregistrée.",
        "de": "✅ Notiz *{name}* gespeichert.",
        "ru": "✅ Заметка *{name}* сохранена.",
        "pt": "✅ Nota *{name}* salva.",
        "ar": "✅ تم حفظ الملحوظة *{name}*.",
        "hi": "✅ नोट *{name}* सहेजा गया।",
        "tr": "✅ *{name}* notu kaydedildi.",
        "id": "✅ Catatan *{name}* disimpan.",
        "th": "✅ บันทึกย่อ *{name}* ถูกบันทึกแล้ว",
    },
    "note_deleted": {
        "en": "✅ Note *{name}* deleted.",
        "es": "✅ Nota *{name}* eliminada.",
        "fr": "✅ Note *{name}* supprimée.",
        "de": "✅ Notiz *{name}* gelöscht.",
        "ru": "✅ Заметка *{name}* удалена.",
        "pt": "✅ Nota *{name}* excluída.",
        "ar": "✅ تم حذف الملحوظة *{name}*.",
        "hi": "✅ नोट *{name}* हटा दिया गया।",
        "tr": "✅ *{name}* notu silindi.",
        "id": "✅ Catatan *{name}* dihapus.",
        "th": "✅ บันทึกย่อ *{name}* ถูกลบแล้ว",
    },
    "note_not_found": {
        "en": "❌ No note found with name: *{name}*",
        "es": "❌ No se encontró ninguna nota con el nombre: *{name}*",
        "fr": "❌ Aucune note trouvée avec le nom: *{name}*",
        "de": "❌ Keine Notiz mit dem Namen gefunden: *{name}*",
        "ru": "❌ Заметка с именем *{name}* не найдена",
        "pt": "❌ Nenhuma nota encontrada com o nome: *{name}*",
        "ar": "❌ لم يتم العثور على ملحوظة بالاسم: *{name}*",
        "hi": "❌ इस नाम से कोई नोट नहीं मिला: *{name}*",
        "tr": "❌ *{name}* adında bir not bulunamadı.",
        "id": "❌ Tidak ada catatan yang ditemukan dengan nama: *{name}*",
        "th": "❌ ไม่พบบันทึกย่อที่มีชื่อ: *{name}*",
    },
    "notes_empty": {
        "en": "📝 No notes saved in this group.",
        "es": "📝 No hay notas guardadas en este grupo.",
        "fr": "📝 Aucune note enregistrée dans ce groupe.",
        "de": "📝 Keine Notizen in dieser Gruppe gespeichert.",
        "ru": "📝 В этой группе нет сохранённых заметок.",
        "pt": "📝 Nenhuma nota salva neste grupo.",
        "ar": "📝 لا يوجد ملحوظات محفوظة في هذه المجموعة.",
        "hi": "📝 इस समूह में कोई नोट सहेजा नहीं गया है।",
        "tr": "📝 Bu grupta kayıtlı not yok.",
        "id": "📝 Tidak ada catatan yang disimpan di grup ini.",
        "th": "📝 ไม่มีบันทึกย่อที่บันทึกไว้ในกลุ่มนี้",
    },
    "welcome_updated": {
        "en": "✅ Welcome message updated.",
        "es": "✅ Mensaje de bienvenida actualizado.",
        "fr": "✅ Message de bienvenue mis à jour.",
        "de": "✅ Willkommensnachricht aktualisiert.",
        "ru": "✅ Приветственное сообщение обновлено.",
        "pt": "✅ Mensagem de boas-vindas atualizada.",
        "ar": "✅ تم تحديث رسالة الترحيب.",
        "hi": "✅ स्वागत संदेश अपडेट किया गया।",
        "tr": "✅ Karşılama mesajı güncellendi.",
        "id": "✅ Pesan selamat datang diperbarui.",
        "th": "✅ อัปเดตข้อความต้อนรับแล้ว",
    },
    "goodbye_updated": {
        "en": "✅ Goodbye message updated.",
        "es": "✅ Mensaje de despedida actualizado.",
        "fr": "✅ Message de revoir mis à jour.",
        "de": "✅ Abschiedsnachricht aktualisiert.",
        "ru": "✅ Прощальное сообщение обновлено.",
        "pt": "✅ Mensagem de despedida atualizada.",
        "ar": "✅ تم تحديث رسالة الوداع.",
        "hi": "✅ विदाई संदेश अपडेट किया गया।",
        "tr": "✅ Veda mesajı güncellendi.",
        "id": "✅ Pesan selamat tinggal diperbarui.",
        "th": "✅ อัปเดตข้อความอำลาแล้ว",
    },
    "rules_updated": {
        "en": "✅ Rules updated.",
        "es": "✅ Reglas actualizadas.",
        "fr": "✅ Règles mises à jour.",
        "de": "✅ Regeln aktualisiert.",
        "ru": "✅ Правила обновлены.",
        "pt": "✅ Regras atualizadas.",
        "ar": "✅ تم تحديث القواعد.",
        "hi": "✅ नियम अपडेट किए गए।",
        "tr": "✅ Kurallar güncellendi.",
        "id": "✅ Aturan diperbarui.",
        "th": "✅ อัปเดตกฎแล้ว",
    },
    "welcome_reset": {
        "en": "✅ Welcome message reset to default.",
        "es": "✅ Mensaje de bienvenida restablecido al predeterminado.",
        "fr": "✅ Message de bienvenue réinitialisé par défaut.",
        "de": "✅ Willkommensnachricht auf Standard zurückgesetzt.",
        "ru": "✅ Приветственное сообщение сброшено до стандартного.",
        "pt": "✅ Mensagem de boas-vindas redefinida para o padrão.",
        "ar": "✅ تم إعادة تعيين رسالة الترحيب إلى الافتراضي.",
        "hi": "✅ स्वागत संदेश डिफ़ॉल्ट पर रीसेट किया गया।",
        "tr": "✅ Karşılama mesajı varsayılana sıfırlandı.",
        "id": "✅ Pesan selamat datang diatur ulang ke default.",
        "th": "✅ รีเซ็ตข้อความต้อนรับเป็นค่าเริ่มต้นแล้ว",
    },
    "rules_empty": {
        "en": "📋 No rules set for this group yet.",
        "es": "📋 Aún no se han establecido reglas para este grupo.",
        "fr": "📋 Aucune règle n'a encore été définie pour ce groupe.",
        "de": "📋 Für diese Gruppe wurden noch keine Regeln festgelegt.",
        "ru": "📋 Для этой группы ещё не установлены правила.",
        "pt": "📋 Nenhuma regra definida para este grupo ainda.",
        "ar": "📋 لم يتم تعيين قواعد لهذه المجموعة بعد.",
        "hi": "📋 इस समूह के लिए अभी तक कोई नियम निर्धारित नहीं किए गए हैं।",
        "tr": "📋 Bu grup için henüz kural belirlenmemiş.",
        "id": "📋 Belum ada aturan yang ditetapkan untuk grup ini.",
        "th": "📋 ยังไม่มีการตั้งกฎสำหรับกลุ่มนี้",
    },
    "vote_admin_only": {
        "en": "❌ This command is for admins only.",
        "es": "❌ Este comando es solo para administradores.",
        "fr": "❌ Cette commande est réservée aux administrateurs.",
        "de": "❌ Dieser Befehl ist nur für Administratoren.",
        "ru": "❌ Эта команда только для администраторов.",
        "pt": "❌ Este comando é apenas para administradores.",
        "ar": "❌ هذا الأمر للمسؤولين فقط.",
        "hi": "❌ यह कमांड केवल एडमिन के लिए है।",
        "tr": "❌ Bu komut sadece yöneticiler içindir.",
        "id": "❌ Perintah ini hanya untuk admin.",
        "th": "❌ คำสั่งนี้สำหรับผู้ดูแลระบบเท่านั้น",
    },
    "vote_no_bot_target": {
        "en": "❌ Can't vote on bot messages.",
        "es": "❌ No se puede votar en mensajes de bots.",
        "fr": "❌ Impossible de voter sur les messages des bots.",
        "de": "❌ Auf Bot-Nachrichten kann nicht abgestimmt werden.",
        "ru": "❌ Нельзя голосовать за сообщения ботов.",
        "pt": "❌ No es posible votar en mensajes de bots.",
        "ar": "❌ لا يمكن التصويت على رسائل البوت.",
        "hi": "❌ बॉट संदेशों पर मतदान नहीं किया जा सकता।",
        "tr": "❌ Bot mesajlarına oy verilemez.",
        "id": "❌ Tidak dapat memilih pesan bot.",
        "th": "❌ ไม่สามารถโหวตข้อความของบอทได้",
    },
    "report_received": {
        "en": "📢 Report received. Admins have been notified.",
        "es": "📢 Reporte recibido. Los administradores han sido notificados.",
        "fr": "📢 Signalement reçu. Les administrateurs ont été notifiés.",
        "de": "📢 Meldung erhalten. Administratoren wurden benachrichtigt.",
        "ru": "📢 Жалоба получена. Администраторы уведомлены.",
        "pt": "📢 Denúncia recebida. Os administradores foram notificados.",
        "ar": "📢 تم استلام البلاغ. تم إخطار المسؤولين.",
        "hi": "📢 रिपोर्ट प्राप्त हुई। एडमिन को सूचित कर दिया गया है।",
        "tr": "📢 Rapor alındı. Yöneticiler bilgilendirildi.",
        "id": "📢 Laporan diterima. Admin telah diberitahu.",
        "th": "📢 ได้รับการรายงานแล้ว ผู้ดูแลระบบได้รับแจ้งแล้ว",
    },
    "redeem_success": {
        "en": "✅ Code redeemed! You received: {reward}",
        "es": "✅ ¡Código canjeado! Recibiste: {reward}",
        "fr": "✅ Code utilisé ! Vous avez reçu : {reward}",
        "de": "✅ Code eingelöst! Du hast erhalten: {reward}",
        "ru": "✅ Код активирован! Вы получили: {reward}",
        "pt": "✅ Código resgatado! Você recebeu: {reward}",
        "ar": "✅ تم استخدام الكود! لقد حصلت على: {reward}",
        "hi": "✅ कोड रिडीम किया गया! आपको प्राप्त हुआ: {reward}",
        "tr": "✅ Kod kullanıldı! Şunu aldınız: {reward}",
        "id": "✅ Kode ditukarkan! Anda menerima: {reward}",
        "th": "✅ ใช้รหัสสำเร็จ! คุณได้รับ: {reward}",
    },
    "redeem_invalid": {
        "en": "❌ Invalid or expired code.",
        "es": "❌ Código inválido o expirado.",
        "fr": "❌ Code invalide ou expiré.",
        "de": "❌ Ungültiger oder abgelaufener Code.",
        "ru": "❌ Неверный или истекший код.",
        "pt": "❌ Código inválido ou expirado.",
        "ar": "❌ كود غير صالح أو منتهي الصلاحية.",
        "hi": "❌ अमान्य या समाप्त कोड।",
        "tr": "❌ Geçersiz veya süresi dolmuş kod.",
        "id": "❌ Kode tidak valid atau kedaluwarsa.",
        "th": "❌ รหัสไม่ถูกต้องหรือหมดอายุ",
    },

}


class LocaleProxy:
    """
    Clean integration for localization.
    Usage: locale.get("warn_user", user="@username", reason="spam", count=1, limit=3)
    """

    def __init__(self, language_code: str = DEFAULT_LANG):
        self.language_code = language_code if language_code in SUPPORTED_LANGUAGES else DEFAULT_LANG

    def get(self, key: str, **kwargs) -> str:
        """Get a localized string by key with optional formatting."""
        if key not in STRINGS:
            logger.warning(f"Missing translation key: {key}")
            return key

        translations = STRINGS[key]
        text = translations.get(self.language_code, translations.get(DEFAULT_LANG, key))

        if kwargs:
            try:
                text = text.format(**kwargs)
            except KeyError as e:
                logger.warning(f"Missing format arg {e} for key {key}")

        return text

    def __call__(self, key: str, **kwargs) -> str:
        """Allow locale("key") syntax."""
        return self.get(key, **kwargs)


def get_locale(language_code: Optional[str] = None) -> LocaleProxy:
    """Get a locale proxy for the given language code."""
    return LocaleProxy(language_code or DEFAULT_LANG)


async def get_user_language(pool, user_id: int) -> str:
    """Get user's preferred language from database."""
    try:
        async with pool.acquire() as conn:
            row = await conn.fetchrow(
                "SELECT language_code FROM user_lang_prefs WHERE user_id = $1", user_id
            )
            if row:
                return row["language_code"]
    except Exception as e:
        logger.debug(f"Failed to get user language: {e}")
    return DEFAULT_LANG


async def set_user_language(pool, user_id: int, language_code: str) -> bool:
    """Set user's preferred language in database."""
    if language_code not in SUPPORTED_LANGUAGES:
        return False

    try:
        async with pool.acquire() as conn:
            await conn.execute(
                """INSERT INTO user_lang_prefs (user_id, language_code)
                   VALUES ($1, $2)
                   ON CONFLICT (user_id) DO UPDATE
                   SET language_code = EXCLUDED.language_code, updated_at = NOW()""",
                user_id,
                language_code,
            )
        return True
    except Exception as e:
        logger.error(f"Failed to set user language: {e}")
        return False


async def get_group_language(pool, chat_id: int) -> str:
    """Get group's default language from database."""
    try:
        async with pool.acquire() as conn:
            row = await conn.fetchrow(
                "SELECT settings->>'default_language' as lang FROM groups WHERE chat_id = $1",
                chat_id,
            )
            if row and row["lang"]:
                return row["lang"]
    except Exception as e:
        logger.debug(f"Failed to get group language: {e}")
    return DEFAULT_LANG


async def get_user_lang(pool, user_id: int, chat_id: int = None) -> str:
    """
    Get user's effective language for messages.

    Priority:
    1. User's stored preference (any) - manual or auto-detected
    2. Group's default language
    3. English (fallback)

    This function always returns a valid language code - never None.
    """
    # Try user preference first
    user_lang = await get_user_language(pool, user_id)
    if user_lang and user_lang in SUPPORTED_LANGUAGES:
        return user_lang

    # Fall back to group language
    if chat_id:
        group_lang = await get_group_language(pool, chat_id)
        if group_lang and group_lang in SUPPORTED_LANGUAGES:
            return group_lang

    # Final fallback
    return DEFAULT_LANG


def get_trust_level(score: int) -> str:
    """Get trust level description based on score."""
    if score >= 90:
        return "Trusted 🟢"
    elif score >= 70:
        return "Reliable 🟡"
    elif score >= 50:
        return "Neutral ⚪"
    elif score >= 30:
        return "Suspicious 🟠"
    else:
        return "Untrusted 🔴"


# Compatibility aliases for v21 upload code
LANGUAGES = SUPPORTED_LANGUAGES


# get_user_lang is defined below as an async function


# Export for convenience
__all__ = [
    "LocaleProxy",
    "get_locale",
    "get_user_language",
    "get_user_lang",
    "set_user_language",
    "get_group_language",
    "SUPPORTED_LANGUAGES",
    "DEFAULT_LANG",
    "get_trust_level",
    "LANGUAGES",
]
